2024-03-28 09:54:12,850 INFO    StreamThr :10416 [internal.py:wandb_internal():86] W&B internal server running at pid: 10416, started at: 2024-03-28 09:54:12.849319
2024-03-28 09:54:12,853 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status
2024-03-28 09:54:12,874 INFO    WriterThread:10416 [datastore.py:open_for_write():87] open: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095412-fihoicz2\run-fihoicz2.wandb
2024-03-28 09:54:12,876 DEBUG   SenderThread:10416 [sender.py:send():378] send: header
2024-03-28 09:54:12,878 DEBUG   SenderThread:10416 [sender.py:send():378] send: run
2024-03-28 09:54:13,892 INFO    SenderThread:10416 [dir_watcher.py:__init__():211] watching files in: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095412-fihoicz2\files
2024-03-28 09:54:13,892 INFO    SenderThread:10416 [sender.py:_start_run_threads():1099] run started: fihoicz2 with start time 1711599852.852307
2024-03-28 09:54:13,909 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: check_version
2024-03-28 09:54:13,910 DEBUG   SenderThread:10416 [sender.py:send_request():405] send_request: check_version
2024-03-28 09:54:14,331 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: run_start
2024-03-28 09:54:14,363 DEBUG   HandlerThread:10416 [system_info.py:__init__():26] System info init
2024-03-28 09:54:14,363 DEBUG   HandlerThread:10416 [system_info.py:__init__():41] System info init done
2024-03-28 09:54:14,363 INFO    HandlerThread:10416 [system_monitor.py:start():194] Starting system monitor
2024-03-28 09:54:14,364 INFO    SystemMonitor:10416 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-28 09:54:14,364 INFO    HandlerThread:10416 [system_monitor.py:probe():214] Collecting system info
2024-03-28 09:54:14,371 INFO    SystemMonitor:10416 [interfaces.py:start():190] Started cpu monitoring
2024-03-28 09:54:14,372 INFO    SystemMonitor:10416 [interfaces.py:start():190] Started disk monitoring
2024-03-28 09:54:14,373 INFO    SystemMonitor:10416 [interfaces.py:start():190] Started gpu monitoring
2024-03-28 09:54:14,374 INFO    SystemMonitor:10416 [interfaces.py:start():190] Started memory monitoring
2024-03-28 09:54:14,387 INFO    SystemMonitor:10416 [interfaces.py:start():190] Started network monitoring
2024-03-28 09:54:14,397 DEBUG   HandlerThread:10416 [system_info.py:probe():150] Probing system
2024-03-28 09:54:14,399 DEBUG   HandlerThread:10416 [gitlib.py:_init_repo():56] git repository is invalid
2024-03-28 09:54:14,399 DEBUG   HandlerThread:10416 [system_info.py:probe():198] Probing system done
2024-03-28 09:54:14,399 DEBUG   HandlerThread:10416 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.13', 'heartbeatAt': '2024-03-28T04:24:14.397832', 'startedAt': '2024-03-28T04:24:12.828834', 'docker': None, 'cuda': None, 'args': ('8000',), 'state': 'running', 'program': 'C:\\Users\\chinm\\Desktop\\FL-FINAL\\MNIST\\client1.py', 'codePathLocal': 'client1.py', 'codePath': 'client1.py', 'host': 'MSI', 'username': 'chinm', 'executable': 'C:\\Users\\chinm\\anaconda3\\New folder\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2496.0, 'min': 0.0, 'max': 2496.0}, 'cpu_freq_per_core': [{'current': 2496.0, 'min': 0.0, 'max': 2496.0}], 'disk': {'/': {'total': 458.81444931030273, 'used': 428.9381446838379}}, 'gpu': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 7.8259735107421875}}
2024-03-28 09:54:14,399 INFO    HandlerThread:10416 [system_monitor.py:probe():224] Finished collecting system info
2024-03-28 09:54:14,399 INFO    HandlerThread:10416 [system_monitor.py:probe():227] Publishing system info
2024-03-28 09:54:14,399 DEBUG   HandlerThread:10416 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-03-28 09:54:14,404 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:14,909 INFO    Thread-16 :10416 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095412-fihoicz2\files\conda-environment.yaml
2024-03-28 09:54:16,418 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:18,428 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:20,447 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:22,465 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:24,482 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:26,497 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:28,526 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:30,543 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:32,559 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:32,599 DEBUG   HandlerThread:10416 [system_info.py:_save_conda():219] Saving conda packages done
2024-03-28 09:54:32,601 INFO    HandlerThread:10416 [system_monitor.py:probe():229] Finished publishing system info
2024-03-28 09:54:32,619 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:32,619 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:54:32,619 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:32,619 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:54:32,619 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:32,619 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:54:32,619 DEBUG   SenderThread:10416 [sender.py:send():378] send: files
2024-03-28 09:54:32,619 INFO    SenderThread:10416 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-03-28 09:54:33,084 INFO    Thread-16 :10416 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095412-fihoicz2\files\conda-environment.yaml
2024-03-28 09:54:33,085 INFO    Thread-16 :10416 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095412-fihoicz2\files\wandb-metadata.json
2024-03-28 09:54:33,351 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: python_packages
2024-03-28 09:54:33,352 DEBUG   SenderThread:10416 [sender.py:send_request():405] send_request: python_packages
2024-03-28 09:54:33,352 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:54:33,354 DEBUG   SenderThread:10416 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:54:33,356 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:54:34,096 INFO    Thread-16 :10416 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095412-fihoicz2\files\requirements.txt
2024-03-28 09:54:34,312 DEBUG   SenderThread:10416 [sender.py:send():378] send: telemetry
2024-03-28 09:54:34,312 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:34,582 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:34,743 INFO    wandb-upload_0:10416 [upload_job.py:push():131] Uploaded file C:\Users\chinm\AppData\Local\Temp\tmp_b02skbewandb\e6ik4kll-wandb-metadata.json
2024-03-28 09:54:35,106 INFO    Thread-16 :10416 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095412-fihoicz2\files\output.log
2024-03-28 09:54:36,604 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:37,128 INFO    Thread-16 :10416 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095412-fihoicz2\files\output.log
2024-03-28 09:54:38,622 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:39,383 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:40,638 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:42,649 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:44,429 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:44,713 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:46,188 INFO    Thread-16 :10416 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095412-fihoicz2\files\config.yaml
2024-03-28 09:54:46,732 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:48,355 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:54:48,355 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:54:48,356 DEBUG   SenderThread:10416 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:54:48,758 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:50,778 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:50,815 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:52,787 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:54,811 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:55,839 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:54:56,831 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:54:58,870 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:00,893 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:00,901 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:55:02,934 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:03,354 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:55:03,354 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:55:03,355 DEBUG   SenderThread:10416 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:55:04,960 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:06,774 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:55:06,982 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:09,003 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:11,015 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:11,807 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:55:13,031 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:14,395 DEBUG   SystemMonitor:10416 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-28 09:55:14,396 DEBUG   SenderThread:10416 [sender.py:send():378] send: stats
2024-03-28 09:55:15,082 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:17,096 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:17,430 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:55:18,347 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:55:18,363 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:55:18,364 DEBUG   SenderThread:10416 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:55:19,117 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:21,144 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:22,804 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:55:23,164 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:25,184 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:27,214 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:27,849 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:55:29,253 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:30,538 INFO    Thread-16 :10416 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095412-fihoicz2\files\output.log
2024-03-28 09:55:31,291 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:32,544 INFO    Thread-16 :10416 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095412-fihoicz2\files\output.log
2024-03-28 09:55:32,906 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:55:33,357 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:55:33,358 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:33,372 DEBUG   HandlerThread:10416 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 09:55:33,372 DEBUG   SenderThread:10416 [sender.py:send_request():405] send_request: stop_status
2024-03-28 09:55:34,584 INFO    Thread-16 :10416 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095412-fihoicz2\files\output.log
2024-03-28 09:55:35,371 ERROR   gpu       :10416 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:55:36,606 INFO    Thread-16 :10416 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240328_095412-fihoicz2\files\output.log
2024-03-28 09:55:36,706 INFO    memory    :10416 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-03-28 09:55:36,706 DEBUG   SystemMonitor:10416 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-28 09:55:36,706 DEBUG   SystemMonitor:10416 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-28 09:55:36,706 DEBUG   SenderThread:10416 [sender.py:send():378] send: stats
2024-03-28 09:55:38,107 INFO    MainThread:10416 [internal.py:handle_exit():76] Internal process exited
