2024-03-18 11:37:34,842 INFO    StreamThr :16356 [internal.py:wandb_internal():86] W&B internal server running at pid: 16356, started at: 2024-03-18 11:37:34.836302
2024-03-18 11:37:34,849 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status
2024-03-18 11:37:34,867 INFO    WriterThread:16356 [datastore.py:open_for_write():87] open: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_113734-18jyi0yz\run-18jyi0yz.wandb
2024-03-18 11:37:34,867 DEBUG   SenderThread:16356 [sender.py:send():378] send: header
2024-03-18 11:37:34,867 DEBUG   SenderThread:16356 [sender.py:send():378] send: run
2024-03-18 11:37:35,987 INFO    SenderThread:16356 [dir_watcher.py:__init__():211] watching files in: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_113734-18jyi0yz\files
2024-03-18 11:37:35,987 INFO    SenderThread:16356 [sender.py:_start_run_threads():1099] run started: 18jyi0yz with start time 1710742054.84521
2024-03-18 11:37:36,010 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: check_version
2024-03-18 11:37:36,010 DEBUG   SenderThread:16356 [sender.py:send_request():405] send_request: check_version
2024-03-18 11:37:36,140 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: run_start
2024-03-18 11:37:37,345 DEBUG   HandlerThread:16356 [system_info.py:__init__():26] System info init
2024-03-18 11:37:37,345 DEBUG   HandlerThread:16356 [system_info.py:__init__():41] System info init done
2024-03-18 11:37:37,345 INFO    HandlerThread:16356 [system_monitor.py:start():194] Starting system monitor
2024-03-18 11:37:37,345 INFO    SystemMonitor:16356 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-18 11:37:37,345 INFO    HandlerThread:16356 [system_monitor.py:probe():214] Collecting system info
2024-03-18 11:37:37,355 INFO    SystemMonitor:16356 [interfaces.py:start():190] Started cpu monitoring
2024-03-18 11:37:37,355 INFO    SystemMonitor:16356 [interfaces.py:start():190] Started disk monitoring
2024-03-18 11:37:37,356 INFO    SystemMonitor:16356 [interfaces.py:start():190] Started gpu monitoring
2024-03-18 11:37:37,356 INFO    SystemMonitor:16356 [interfaces.py:start():190] Started memory monitoring
2024-03-18 11:37:37,359 INFO    SystemMonitor:16356 [interfaces.py:start():190] Started network monitoring
2024-03-18 11:37:37,379 DEBUG   HandlerThread:16356 [system_info.py:probe():150] Probing system
2024-03-18 11:37:37,382 DEBUG   HandlerThread:16356 [gitlib.py:_init_repo():56] git repository is invalid
2024-03-18 11:37:37,382 DEBUG   HandlerThread:16356 [system_info.py:probe():198] Probing system done
2024-03-18 11:37:37,382 DEBUG   HandlerThread:16356 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.13', 'heartbeatAt': '2024-03-18T06:07:37.380423', 'startedAt': '2024-03-18T06:07:34.773987', 'docker': None, 'cuda': None, 'args': ('8000',), 'state': 'running', 'program': 'C:\\Users\\chinm\\Desktop\\FL-FINAL\\MNIST\\server.py', 'codePathLocal': 'server.py', 'codePath': 'server.py', 'host': 'MSI', 'username': 'chinm', 'executable': 'C:\\Users\\chinm\\anaconda3\\New folder\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2496.0, 'min': 0.0, 'max': 2496.0}, 'cpu_freq_per_core': [{'current': 2496.0, 'min': 0.0, 'max': 2496.0}], 'disk': {'/': {'total': 458.81444931030273, 'used': 431.1469917297363}}, 'gpu': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 7.8259735107421875}}
2024-03-18 11:37:37,382 INFO    HandlerThread:16356 [system_monitor.py:probe():224] Finished collecting system info
2024-03-18 11:37:37,382 INFO    HandlerThread:16356 [system_monitor.py:probe():227] Publishing system info
2024-03-18 11:37:37,382 DEBUG   HandlerThread:16356 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-03-18 11:37:37,386 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:37:38,010 INFO    Thread-16 :16356 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_113734-18jyi0yz\files\conda-environment.yaml
2024-03-18 11:37:40,038 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:37:40,038 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:37:42,677 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:37:42,677 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:37:45,315 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:37:45,315 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:37:47,979 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:37:47,979 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:37:50,632 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:37:50,632 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:37:53,283 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:37:53,283 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:37:54,013 DEBUG   HandlerThread:16356 [system_info.py:_save_conda():219] Saving conda packages done
2024-03-18 11:37:54,013 INFO    HandlerThread:16356 [system_monitor.py:probe():229] Finished publishing system info
2024-03-18 11:37:54,031 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:37:54,031 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:37:54,031 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:37:54,031 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:37:54,031 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:37:54,031 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:37:54,031 DEBUG   SenderThread:16356 [sender.py:send():378] send: files
2024-03-18 11:37:54,031 INFO    SenderThread:16356 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-03-18 11:37:54,134 INFO    Thread-16 :16356 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_113734-18jyi0yz\files\conda-environment.yaml
2024-03-18 11:37:54,134 INFO    Thread-16 :16356 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_113734-18jyi0yz\files\wandb-metadata.json
2024-03-18 11:37:54,848 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: python_packages
2024-03-18 11:37:54,848 DEBUG   SenderThread:16356 [sender.py:send_request():405] send_request: python_packages
2024-03-18 11:37:54,848 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:37:54,848 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:37:54,848 DEBUG   SenderThread:16356 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:37:55,148 INFO    Thread-16 :16356 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_113734-18jyi0yz\files\requirements.txt
2024-03-18 11:37:55,195 INFO    wandb-upload_0:16356 [upload_job.py:push():131] Uploaded file C:\Users\chinm\AppData\Local\Temp\tmpgptm9rljwandb\wgsfokhv-wandb-metadata.json
2024-03-18 11:37:55,226 DEBUG   SenderThread:16356 [sender.py:send():378] send: telemetry
2024-03-18 11:37:55,941 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:37:55,941 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:37:56,154 INFO    Thread-16 :16356 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_113734-18jyi0yz\files\output.log
2024-03-18 11:37:56,249 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:37:58,182 INFO    Thread-16 :16356 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_113734-18jyi0yz\files\output.log
2024-03-18 11:37:58,580 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:37:58,580 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:01,238 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:01,238 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:01,285 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:38:03,888 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:03,888 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:06,322 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:38:06,527 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:06,527 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:07,253 INFO    Thread-16 :16356 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_113734-18jyi0yz\files\config.yaml
2024-03-18 11:38:09,165 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:09,165 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:09,868 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:38:09,870 DEBUG   SenderThread:16356 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:38:09,870 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:38:10,271 INFO    Thread-16 :16356 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_113734-18jyi0yz\files\output.log
2024-03-18 11:38:11,832 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:11,832 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:12,256 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:38:14,486 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:14,486 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:17,173 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:17,173 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:17,312 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:38:19,840 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:19,840 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:22,349 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:38:22,489 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:22,489 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:24,881 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:38:24,882 DEBUG   SenderThread:16356 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:38:24,882 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:38:25,123 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:25,123 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:27,803 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:27,803 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:28,242 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:38:30,453 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:30,453 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:33,110 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:33,110 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:33,285 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:38:35,777 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:35,777 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:37,368 DEBUG   SystemMonitor:16356 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-18 11:38:37,369 DEBUG   SenderThread:16356 [sender.py:send():378] send: stats
2024-03-18 11:38:38,387 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:38:38,438 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:38,438 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:39,894 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:38:39,894 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:38:39,897 DEBUG   SenderThread:16356 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:38:41,094 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:41,094 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:43,758 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:43,758 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:44,372 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:38:46,408 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:46,408 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:49,078 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:49,078 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:49,434 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:38:51,739 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:51,739 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:54,398 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:54,398 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:54,467 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:38:54,887 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:38:54,888 DEBUG   SenderThread:16356 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:38:54,902 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:38:57,088 ERROR   gpu       :16356 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:38:57,098 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:57,098 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:59,782 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:59,782 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:38:59,915 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:39:02,457 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:02,458 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:04,952 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:39:05,099 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:05,099 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:07,769 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:07,769 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:09,908 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:39:10,432 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:10,432 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:13,088 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:13,088 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:15,028 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:39:15,758 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:15,758 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:16,491 DEBUG   SenderThread:16356 [sender.py:send():378] send: stats
2024-03-18 11:39:16,491 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:39:18,432 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:18,432 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:20,028 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:39:21,119 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:21,139 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:21,530 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:39:23,802 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:23,802 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:24,918 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:39:26,467 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:26,468 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:26,560 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:39:26,978 WARNING FileStreamThread:16356 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001F1ED9C2DF0>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinnu1/flower_server/18jyi0yz/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-03-18 11:39:29,162 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:29,162 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:30,094 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:39:31,601 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:39:31,848 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:31,848 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:34,504 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:34,504 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:35,130 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:39:36,638 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:39:37,188 ERROR   gpu       :16356 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:39:37,198 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:37,198 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:37,378 DEBUG   SenderThread:16356 [sender.py:send():378] send: stats
2024-03-18 11:39:39,884 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:39,884 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:39,922 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:39:42,404 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:39:42,554 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:42,557 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:45,209 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:45,210 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:45,210 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:39:47,434 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:39:47,888 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:47,888 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:50,231 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:39:50,551 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:50,551 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:52,464 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:39:53,199 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:53,199 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:54,933 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:39:55,858 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:55,858 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:57,511 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:39:58,514 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:39:58,514 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:00,279 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:40:01,165 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:01,165 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:02,550 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:40:03,826 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:03,826 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:05,319 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:40:06,465 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:06,465 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:07,389 DEBUG   SenderThread:16356 [sender.py:send():378] send: stats
2024-03-18 11:40:08,401 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:40:09,134 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:09,134 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:09,938 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:40:11,780 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:11,780 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:13,434 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:40:14,434 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:14,434 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:15,377 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:40:17,117 ERROR   gpu       :16356 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:40:17,125 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:17,125 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:18,452 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:40:19,786 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:19,786 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:20,403 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:40:22,453 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:22,453 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:23,461 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:40:24,951 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:40:25,119 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:25,124 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:27,774 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:27,774 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:28,527 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:40:30,440 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:30,440 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:30,476 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:40:33,098 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:33,098 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:33,604 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:40:35,511 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:40:35,769 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:35,769 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:37,396 DEBUG   SenderThread:16356 [sender.py:send():378] send: stats
2024-03-18 11:40:38,426 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:38,426 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:39,416 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:40:39,966 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:40:41,111 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:41,114 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:43,768 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:43,768 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:44,440 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:40:45,603 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:40:46,436 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:46,436 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:49,077 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:49,077 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:49,470 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:40:50,632 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:40:51,763 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:51,763 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:54,404 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:54,404 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:54,506 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:40:54,977 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:40:56,615 WARNING FileStreamThread:16356 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001F1ED9C2DF0>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinnu1/flower_server/18jyi0yz/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 4, 'content': ['{"system.proc.memory.availableMB": 1123.53, "system.memory": 85.99, "system.proc.memory.rssMB": 305.19, "system.proc.memory.percent": 3.81, "system.cpu": 0.0, "system.cpu.0.cpu_percent": 9.44, "system.cpu.1.cpu_percent": 2.43, "system.cpu.2.cpu_percent": 7.45, "system.cpu.3.cpu_percent": 6.58, "system.cpu.4.cpu_percent": 8.81, "system.cpu.5.cpu_percent": 3.34, "system.cpu.6.cpu_percent": 8.22, "system.cpu.7.cpu_percent": 5.31, "system.cpu.8.cpu_percent": 6.46, "system.cpu.9.cpu_percent": 3.05, "system.cpu.10.cpu_percent": 7.65, "system.cpu.11.cpu_percent": 7.23, "system.proc.cpu.threads": 48, "system.disk.\\\\.usagePercent": 94.2, "system.disk.\\\\.usageGB": 432.05, "system.disk.in": 514.99, "system.disk.out": 126.89, "system.network.sent": 355558.4, "system.network.recv": 4021176.67, "system.gpu.0.memoryAllocated": 2.56, "system.gpu.0.memoryAllocatedBytes": 110100480.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 53.0, "_wandb": true, "_timestamp": 1710742237.395774, "_runtime": 182.550564}']}}, 'dropped': 0}}
2024-03-18 11:40:57,082 ERROR   gpu       :16356 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:40:57,098 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:57,098 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:59,534 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:40:59,753 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:40:59,753 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:00,677 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:41:02,419 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:02,419 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:04,562 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:41:05,079 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:05,080 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:05,715 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:41:07,401 DEBUG   SenderThread:16356 [sender.py:send():378] send: stats
2024-03-18 11:41:07,723 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:07,723 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:09,982 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:41:10,405 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:10,406 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:10,414 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:41:13,058 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:13,058 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:15,450 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:41:15,725 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:15,725 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:15,788 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:41:18,382 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:18,388 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:20,546 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:41:20,816 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:41:21,026 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:21,041 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:23,697 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:23,697 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:24,993 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:41:25,597 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:41:26,352 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:26,352 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:29,011 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:29,011 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:30,644 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:41:30,870 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:41:31,683 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:31,683 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:34,326 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:34,326 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:35,668 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:41:35,919 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:41:37,016 ERROR   gpu       :16356 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:41:37,024 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:37,024 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:37,411 DEBUG   SenderThread:16356 [sender.py:send():378] send: stats
2024-03-18 11:41:39,685 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:39,685 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:39,998 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:41:41,455 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:41:42,384 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:42,384 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:45,048 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:45,048 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:46,013 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:41:46,478 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:41:47,711 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:47,711 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:50,388 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:50,388 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:51,007 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:41:51,511 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:41:53,041 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:53,041 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:55,009 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:41:55,703 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:55,703 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:56,531 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:41:58,364 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:41:58,364 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:00,079 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:42:01,011 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:01,011 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:01,585 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:42:03,673 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:03,673 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:05,126 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:42:06,360 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:06,360 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:06,607 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:42:07,423 DEBUG   SenderThread:16356 [sender.py:send():378] send: stats
2024-03-18 11:42:09,034 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:09,034 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:10,013 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:42:11,693 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:11,693 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:12,467 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:42:14,349 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:14,349 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:15,196 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:42:17,039 ERROR   gpu       :16356 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:42:17,039 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:17,039 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:17,506 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:42:19,766 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:19,766 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:20,226 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:42:22,420 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:22,420 ERROR   gpu       :16356 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:42:22,537 DEBUG   HandlerThread:16356 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:42:23,911 INFO    cpu       :16356 [interfaces.py:monitor():140] Process cpu has exited.
2024-03-18 11:42:23,912 DEBUG   SystemMonitor:16356 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-18 11:42:23,912 DEBUG   SystemMonitor:16356 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-18 11:42:23,918 DEBUG   SenderThread:16356 [sender.py:send():378] send: stats
2024-03-18 11:42:24,587 ERROR   gpu       :16356 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:42:25,348 INFO    MainThread:16356 [internal.py:handle_exit():76] Internal process exited
