2024-03-18 11:14:59,664 INFO    StreamThr :3396 [internal.py:wandb_internal():86] W&B internal server running at pid: 3396, started at: 2024-03-18 11:14:59.663512
2024-03-18 11:14:59,670 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status
2024-03-18 11:14:59,681 INFO    WriterThread:3396 [datastore.py:open_for_write():87] open: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111459-tgsirv82\run-tgsirv82.wandb
2024-03-18 11:14:59,681 DEBUG   SenderThread:3396 [sender.py:send():378] send: header
2024-03-18 11:14:59,688 DEBUG   SenderThread:3396 [sender.py:send():378] send: run
2024-03-18 11:15:00,581 INFO    SenderThread:3396 [dir_watcher.py:__init__():211] watching files in: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111459-tgsirv82\files
2024-03-18 11:15:00,581 INFO    SenderThread:3396 [sender.py:_start_run_threads():1099] run started: tgsirv82 with start time 1710740699.664037
2024-03-18 11:15:00,591 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: check_version
2024-03-18 11:15:00,591 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: check_version
2024-03-18 11:15:00,747 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: run_start
2024-03-18 11:15:01,941 DEBUG   HandlerThread:3396 [system_info.py:__init__():26] System info init
2024-03-18 11:15:01,941 DEBUG   HandlerThread:3396 [system_info.py:__init__():41] System info init done
2024-03-18 11:15:01,941 INFO    HandlerThread:3396 [system_monitor.py:start():194] Starting system monitor
2024-03-18 11:15:01,941 INFO    SystemMonitor:3396 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-18 11:15:01,941 INFO    HandlerThread:3396 [system_monitor.py:probe():214] Collecting system info
2024-03-18 11:15:01,953 INFO    SystemMonitor:3396 [interfaces.py:start():190] Started cpu monitoring
2024-03-18 11:15:01,953 INFO    SystemMonitor:3396 [interfaces.py:start():190] Started disk monitoring
2024-03-18 11:15:01,953 INFO    SystemMonitor:3396 [interfaces.py:start():190] Started gpu monitoring
2024-03-18 11:15:01,953 INFO    SystemMonitor:3396 [interfaces.py:start():190] Started memory monitoring
2024-03-18 11:15:01,966 INFO    SystemMonitor:3396 [interfaces.py:start():190] Started network monitoring
2024-03-18 11:15:01,972 DEBUG   HandlerThread:3396 [system_info.py:probe():150] Probing system
2024-03-18 11:15:01,974 DEBUG   HandlerThread:3396 [gitlib.py:_init_repo():56] git repository is invalid
2024-03-18 11:15:01,974 DEBUG   HandlerThread:3396 [system_info.py:probe():198] Probing system done
2024-03-18 11:15:01,974 DEBUG   HandlerThread:3396 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.13', 'heartbeatAt': '2024-03-18T05:45:01.972704', 'startedAt': '2024-03-18T05:44:59.623545', 'docker': None, 'cuda': None, 'args': ('8000',), 'state': 'running', 'program': 'C:\\Users\\chinm\\Desktop\\FL-FINAL\\MNIST\\server.py', 'codePathLocal': 'server.py', 'codePath': 'server.py', 'host': 'MSI', 'username': 'chinm', 'executable': 'C:\\Users\\chinm\\anaconda3\\New folder\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2496.0, 'min': 0.0, 'max': 2496.0}, 'cpu_freq_per_core': [{'current': 2496.0, 'min': 0.0, 'max': 2496.0}], 'disk': {'/': {'total': 458.81444931030273, 'used': 431.2173767089844}}, 'gpu': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 7.8259735107421875}}
2024-03-18 11:15:01,974 INFO    HandlerThread:3396 [system_monitor.py:probe():224] Finished collecting system info
2024-03-18 11:15:01,974 INFO    HandlerThread:3396 [system_monitor.py:probe():227] Publishing system info
2024-03-18 11:15:01,974 DEBUG   HandlerThread:3396 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-03-18 11:15:01,974 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:15:02,594 INFO    Thread-16 :3396 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111459-tgsirv82\files\conda-environment.yaml
2024-03-18 11:15:04,619 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:04,619 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:07,263 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:07,263 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:09,924 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:09,924 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:12,571 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:12,572 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:15,226 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:15,226 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:17,869 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:17,869 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:18,016 DEBUG   HandlerThread:3396 [system_info.py:_save_conda():219] Saving conda packages done
2024-03-18 11:15:18,021 INFO    HandlerThread:3396 [system_monitor.py:probe():229] Finished publishing system info
2024-03-18 11:15:18,032 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:15:18,032 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:15:18,032 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:15:18,032 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:15:18,032 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:15:18,032 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:15:18,032 DEBUG   SenderThread:3396 [sender.py:send():378] send: files
2024-03-18 11:15:18,032 INFO    SenderThread:3396 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-03-18 11:15:18,701 INFO    Thread-16 :3396 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111459-tgsirv82\files\conda-environment.yaml
2024-03-18 11:15:18,701 INFO    Thread-16 :3396 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111459-tgsirv82\files\wandb-metadata.json
2024-03-18 11:15:18,808 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: python_packages
2024-03-18 11:15:18,809 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: python_packages
2024-03-18 11:15:18,809 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:15:18,810 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:15:18,810 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:15:19,159 DEBUG   SenderThread:3396 [sender.py:send():378] send: telemetry
2024-03-18 11:15:19,717 INFO    Thread-16 :3396 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111459-tgsirv82\files\output.log
2024-03-18 11:15:19,717 INFO    Thread-16 :3396 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111459-tgsirv82\files\requirements.txt
2024-03-18 11:15:20,031 INFO    wandb-upload_0:3396 [upload_job.py:push():131] Uploaded file C:\Users\chinm\AppData\Local\Temp\tmpffuv9n0owandb\xn055ygc-wandb-metadata.json
2024-03-18 11:15:20,177 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:15:20,529 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:20,529 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:21,723 INFO    Thread-16 :3396 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111459-tgsirv82\files\output.log
2024-03-18 11:15:23,208 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:23,208 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:25,213 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:15:25,874 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:25,874 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:28,548 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:28,549 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:30,253 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:15:30,794 INFO    Thread-16 :3396 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111459-tgsirv82\files\config.yaml
2024-03-18 11:15:31,201 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:31,201 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:33,816 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:15:33,816 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:15:33,816 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:15:33,856 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:33,856 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:36,280 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:15:36,525 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:36,525 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:39,184 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:39,184 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:41,318 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:15:41,909 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:41,909 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:44,568 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:44,568 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:46,346 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:15:47,233 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:47,233 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:48,824 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:15:48,833 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:15:48,833 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:15:49,878 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:49,878 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:52,194 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:15:52,535 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:52,535 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:55,186 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:55,192 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:57,237 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:15:57,844 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:15:57,844 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:00,498 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:00,498 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:01,980 DEBUG   SystemMonitor:3396 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-18 11:16:01,984 DEBUG   SenderThread:3396 [sender.py:send():378] send: stats
2024-03-18 11:16:02,991 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:16:03,157 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:03,157 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:03,825 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:16:03,853 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:16:03,853 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:16:05,846 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:05,846 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:08,310 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:16:08,553 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:08,553 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:11,209 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:11,209 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:13,343 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:16:13,863 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:13,863 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:16,510 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:16,510 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:18,382 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:16:18,833 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:16:18,863 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:16:18,863 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:16:19,162 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:19,162 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:21,821 ERROR   gpu       :3396 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:16:21,837 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:21,837 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:24,346 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:16:24,497 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:24,497 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:27,158 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:27,158 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:29,394 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:16:29,811 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:29,811 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:31,989 DEBUG   SenderThread:3396 [sender.py:send():378] send: stats
2024-03-18 11:16:32,480 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:32,480 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:33,840 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:16:33,857 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:16:33,857 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:16:35,114 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:35,114 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:35,264 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:16:37,751 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:37,751 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:40,285 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:16:40,405 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:40,405 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:43,064 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:43,064 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:45,335 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:16:45,714 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:45,716 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:48,380 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:48,381 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:48,848 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:16:48,864 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:16:48,864 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:16:51,051 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:51,051 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:51,208 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:16:53,708 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:53,708 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:56,240 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:16:56,391 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:56,391 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:59,039 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:16:59,039 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:01,274 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:17:01,724 ERROR   gpu       :3396 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:17:01,734 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:01,734 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:01,996 DEBUG   SenderThread:3396 [sender.py:send():378] send: stats
2024-03-18 11:17:03,857 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:17:03,878 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:17:03,878 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:17:04,410 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:04,410 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:06,386 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:17:07,073 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:07,073 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:09,724 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:09,724 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:11,430 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:17:12,381 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:12,381 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:15,053 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:15,053 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:16,490 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:17:17,718 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:17,718 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:18,867 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:17:18,900 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:17:18,901 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:17:20,374 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:20,374 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:22,282 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:17:23,031 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:23,031 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:25,702 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:25,702 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:27,333 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:17:28,339 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:28,339 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:30,984 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:30,984 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:32,004 DEBUG   SenderThread:3396 [sender.py:send():378] send: stats
2024-03-18 11:17:33,011 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:17:33,648 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:33,648 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:33,885 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:17:33,923 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:17:33,923 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:17:36,303 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:36,303 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:38,183 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:17:38,519 INFO    Thread-16 :3396 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111459-tgsirv82\files\output.log
2024-03-18 11:17:38,959 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:38,959 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:41,663 ERROR   gpu       :3396 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:17:41,672 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:41,672 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:43,240 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:17:44,365 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:44,365 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:47,003 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:47,003 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:48,265 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:17:48,899 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:17:48,930 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:17:48,930 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:17:49,655 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:49,655 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:52,304 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:52,304 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:53,360 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:17:54,972 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:54,972 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:57,635 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:57,635 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:17:58,778 INFO    Thread-16 :3396 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111459-tgsirv82\files\output.log
2024-03-18 11:17:59,038 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:18:00,286 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:00,286 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:02,014 DEBUG   SenderThread:3396 [sender.py:send():378] send: stats
2024-03-18 11:18:02,940 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:02,940 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:03,905 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:18:03,937 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:18:03,937 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:18:04,267 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:18:05,629 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:05,629 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:08,275 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:08,275 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:09,304 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:18:10,952 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:10,952 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:13,635 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:13,635 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:14,350 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:18:16,293 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:16,293 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:18,922 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:18:18,953 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:18:18,953 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:18:18,955 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:18,955 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:20,333 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:18:21,628 ERROR   gpu       :3396 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:18:21,636 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:21,636 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:24,295 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:24,295 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:25,364 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:18:26,949 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:26,949 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:29,616 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:29,616 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:30,397 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:18:32,016 DEBUG   SenderThread:3396 [sender.py:send():378] send: stats
2024-03-18 11:18:32,274 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:32,275 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:33,925 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:18:33,956 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:18:33,957 DEBUG   SenderThread:3396 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:18:34,940 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:34,940 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:36,353 DEBUG   HandlerThread:3396 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:18:37,605 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:37,605 ERROR   gpu       :3396 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:18:38,755 INFO    memory    :3396 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-03-18 11:18:38,755 DEBUG   SystemMonitor:3396 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-18 11:18:38,755 DEBUG   SystemMonitor:3396 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-18 11:18:38,761 DEBUG   SenderThread:3396 [sender.py:send():378] send: stats
2024-03-18 11:18:39,395 ERROR   gpu       :3396 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:18:40,489 INFO    MainThread:3396 [internal.py:handle_exit():76] Internal process exited
