2024-03-18 11:18:54,241 INFO    StreamThr :26192 [internal.py:wandb_internal():86] W&B internal server running at pid: 26192, started at: 2024-03-18 11:18:54.237222
2024-03-18 11:18:54,249 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status
2024-03-18 11:18:54,266 INFO    WriterThread:26192 [datastore.py:open_for_write():87] open: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\run-9qdie3lg.wandb
2024-03-18 11:18:54,266 DEBUG   SenderThread:26192 [sender.py:send():378] send: header
2024-03-18 11:18:54,266 DEBUG   SenderThread:26192 [sender.py:send():378] send: run
2024-03-18 11:18:58,675 INFO    SenderThread:26192 [dir_watcher.py:__init__():211] watching files in: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files
2024-03-18 11:18:58,675 INFO    SenderThread:26192 [sender.py:_start_run_threads():1099] run started: 9qdie3lg with start time 1710740934.248476
2024-03-18 11:18:58,740 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: check_version
2024-03-18 11:18:58,740 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: check_version
2024-03-18 11:18:59,144 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: run_start
2024-03-18 11:19:00,362 DEBUG   HandlerThread:26192 [system_info.py:__init__():26] System info init
2024-03-18 11:19:00,362 DEBUG   HandlerThread:26192 [system_info.py:__init__():41] System info init done
2024-03-18 11:19:00,362 INFO    HandlerThread:26192 [system_monitor.py:start():194] Starting system monitor
2024-03-18 11:19:00,362 INFO    SystemMonitor:26192 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-18 11:19:00,362 INFO    HandlerThread:26192 [system_monitor.py:probe():214] Collecting system info
2024-03-18 11:19:00,362 INFO    SystemMonitor:26192 [interfaces.py:start():190] Started cpu monitoring
2024-03-18 11:19:00,362 INFO    SystemMonitor:26192 [interfaces.py:start():190] Started disk monitoring
2024-03-18 11:19:00,362 INFO    SystemMonitor:26192 [interfaces.py:start():190] Started gpu monitoring
2024-03-18 11:19:00,362 INFO    SystemMonitor:26192 [interfaces.py:start():190] Started memory monitoring
2024-03-18 11:19:00,379 INFO    SystemMonitor:26192 [interfaces.py:start():190] Started network monitoring
2024-03-18 11:19:00,386 DEBUG   HandlerThread:26192 [system_info.py:probe():150] Probing system
2024-03-18 11:19:00,386 DEBUG   HandlerThread:26192 [gitlib.py:_init_repo():56] git repository is invalid
2024-03-18 11:19:00,386 DEBUG   HandlerThread:26192 [system_info.py:probe():198] Probing system done
2024-03-18 11:19:00,386 DEBUG   HandlerThread:26192 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.13', 'heartbeatAt': '2024-03-18T05:49:00.386402', 'startedAt': '2024-03-18T05:48:54.195232', 'docker': None, 'cuda': None, 'args': ('8000',), 'state': 'running', 'program': 'C:\\Users\\chinm\\Desktop\\FL-FINAL\\MNIST\\server.py', 'codePathLocal': 'server.py', 'codePath': 'server.py', 'host': 'MSI', 'username': 'chinm', 'executable': 'C:\\Users\\chinm\\anaconda3\\New folder\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2496.0, 'min': 0.0, 'max': 2496.0}, 'cpu_freq_per_core': [{'current': 2496.0, 'min': 0.0, 'max': 2496.0}], 'disk': {'/': {'total': 458.81444931030273, 'used': 431.23772048950195}}, 'gpu': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 7.8259735107421875}}
2024-03-18 11:19:00,386 INFO    HandlerThread:26192 [system_monitor.py:probe():224] Finished collecting system info
2024-03-18 11:19:00,386 INFO    HandlerThread:26192 [system_monitor.py:probe():227] Publishing system info
2024-03-18 11:19:00,386 DEBUG   HandlerThread:26192 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-03-18 11:19:00,394 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:19:00,700 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\conda-environment.yaml
2024-03-18 11:19:03,054 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:03,054 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:05,697 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:05,697 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:08,346 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:08,346 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:10,994 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:10,994 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:13,637 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:13,637 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:15,411 DEBUG   HandlerThread:26192 [system_info.py:_save_conda():219] Saving conda packages done
2024-03-18 11:19:15,411 INFO    HandlerThread:26192 [system_monitor.py:probe():229] Finished publishing system info
2024-03-18 11:19:15,490 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:19:15,490 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:19:15,490 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:19:15,490 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:19:15,490 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:19:15,490 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: keepalive
2024-03-18 11:19:15,490 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:19:15,490 DEBUG   SenderThread:26192 [sender.py:send():378] send: files
2024-03-18 11:19:15,490 INFO    SenderThread:26192 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-03-18 11:19:15,806 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\conda-environment.yaml
2024-03-18 11:19:15,806 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\wandb-metadata.json
2024-03-18 11:19:16,274 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:16,274 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:16,400 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: python_packages
2024-03-18 11:19:16,400 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: python_packages
2024-03-18 11:19:16,400 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:19:16,400 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:19:16,400 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:19:16,679 DEBUG   SenderThread:26192 [sender.py:send():378] send: telemetry
2024-03-18 11:19:16,821 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\output.log
2024-03-18 11:19:16,821 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\requirements.txt
2024-03-18 11:19:17,502 INFO    wandb-upload_0:26192 [upload_job.py:push():131] Uploaded file C:\Users\chinm\AppData\Local\Temp\tmp81opj_w2wandb\xc7ujpcl-wandb-metadata.json
2024-03-18 11:19:18,832 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\output.log
2024-03-18 11:19:18,926 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:18,926 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:20,707 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:19:21,574 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:21,575 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:24,213 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:24,213 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:25,745 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:19:26,874 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:26,874 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:26,890 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\config.yaml
2024-03-18 11:19:29,516 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:29,516 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:31,085 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:19:31,407 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:19:31,407 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:19:31,411 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:19:32,200 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:32,200 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:34,859 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:34,859 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:36,880 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:19:37,540 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:37,540 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:40,246 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:40,249 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:41,918 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:19:42,920 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:42,920 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:45,582 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:45,582 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:46,400 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:19:46,411 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:19:46,411 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:19:47,718 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:19:48,232 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:48,232 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:50,940 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:50,940 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:52,767 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:19:53,600 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:53,600 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:56,246 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:56,246 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:57,800 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:19:58,890 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:19:58,890 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:00,391 DEBUG   SystemMonitor:26192 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-18 11:20:00,391 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:20:01,413 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:20:01,413 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:20:01,413 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:20:01,540 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:01,540 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:02,843 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:20:04,190 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:04,190 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:06,838 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:06,838 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:07,870 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:20:09,512 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:09,512 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:12,189 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:12,189 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:12,915 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:20:14,845 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:14,848 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:16,420 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:20:16,437 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:20:16,439 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:20:17,499 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:17,499 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:18,778 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:20:20,174 ERROR   gpu       :26192 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:20:20,183 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:20,183 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:22,869 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:22,869 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:23,798 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:20:25,529 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:25,529 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:28,189 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:28,189 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:28,824 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:20:30,404 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:20:30,849 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:30,849 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:31,424 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:20:31,440 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:20:31,440 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:20:33,509 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:33,509 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:33,876 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:20:36,185 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:36,185 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:38,841 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:38,841 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:38,921 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:20:41,493 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:41,506 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:43,953 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:20:44,147 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:44,147 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:46,437 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:20:46,439 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:20:46,440 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:20:46,828 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:46,839 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:49,490 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:49,490 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:49,782 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:20:52,159 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:52,159 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:54,799 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:54,801 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:54,817 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:20:57,438 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:57,438 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:20:59,845 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:21:00,109 ERROR   gpu       :26192 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:21:00,121 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:00,121 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:00,415 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:21:01,442 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:21:01,444 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:21:01,444 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:21:02,789 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:02,789 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:04,869 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:21:05,449 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:05,449 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:08,119 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:08,119 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:09,910 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:21:10,799 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:10,799 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:13,459 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:13,459 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:14,956 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:21:16,115 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:16,115 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:16,453 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:21:16,453 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:21:16,453 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:21:18,783 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:18,783 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:20,940 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:21:21,434 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:21,434 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:24,098 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:24,098 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:25,987 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:21:26,750 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:26,750 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:29,409 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:29,409 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:30,415 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:21:31,427 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:21:31,459 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:21:31,459 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:21:31,459 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:21:32,069 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:32,069 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:34,734 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:34,734 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:36,889 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:21:37,397 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:37,397 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:40,059 ERROR   gpu       :26192 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:21:40,067 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:40,067 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:41,940 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:21:42,723 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:42,723 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:45,406 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:45,410 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:46,465 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:21:46,465 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:21:46,465 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:21:47,881 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:21:48,074 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:48,074 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:50,739 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:50,739 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:52,910 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:21:53,399 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:53,399 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:56,085 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:56,085 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:57,943 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:21:58,742 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:21:58,742 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:00,425 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:22:01,405 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:01,405 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:01,461 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:22:01,461 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:22:01,477 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:22:03,874 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:22:04,055 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:04,055 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:06,711 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:06,711 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:08,927 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:22:09,379 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:09,379 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:12,068 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:12,068 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:13,973 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:22:14,737 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:14,737 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:16,471 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:22:16,471 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:22:16,484 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:22:17,405 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:17,405 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:19,876 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:22:20,083 ERROR   gpu       :26192 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:22:20,093 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:20,093 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:22,754 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:22,754 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:24,906 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:22:25,406 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:25,406 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:28,061 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:28,061 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:29,929 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:22:30,428 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:22:30,713 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:30,713 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:31,468 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:22:31,470 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:22:31,488 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:22:33,375 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:33,375 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:35,849 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:22:36,024 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:36,024 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:38,691 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:38,691 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:40,882 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:22:41,369 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:41,374 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:44,048 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:44,048 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:45,919 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:22:46,474 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:22:46,474 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:22:46,481 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:22:46,705 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:46,705 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:49,375 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:49,375 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:51,870 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:22:52,014 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:52,014 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:54,677 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:54,677 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:56,931 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:22:57,344 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:22:57,348 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:00,034 ERROR   gpu       :26192 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-18 11:23:00,045 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:00,053 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:00,441 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:23:01,484 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:23:01,500 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:23:01,500 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:23:02,725 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:02,725 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:02,857 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:23:05,370 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:05,370 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:07,910 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:23:08,026 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:08,026 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:10,674 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:10,674 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:12,575 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\output.log
2024-03-18 11:23:13,187 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:23:13,379 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:13,379 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:16,039 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:16,039 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:16,490 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:23:16,504 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:23:16,504 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:23:18,700 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:18,700 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:18,872 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:23:21,367 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:21,367 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:23,898 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:23:24,008 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:24,008 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:26,682 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:26,682 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:23:28,883 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\output.log
2024-03-18 11:23:29,008 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:23:29,547 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:23:30,471 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:23:31,515 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:23:31,534 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:23:31,534 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:23:32,402 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:23:34,856 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:23:35,242 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:23:38,141 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:23:39,944 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:23:41,146 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:23:44,018 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:23:45,016 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:23:46,502 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:23:46,551 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:23:46,553 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:23:46,875 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:23:49,694 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:23:50,031 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:23:52,537 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:23:55,315 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:23:55,380 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:23:58,264 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:24:00,493 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:24:00,497 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:24:01,137 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:24:01,511 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:24:01,542 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:24:01,546 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:24:04,020 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:24:06,086 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:24:06,797 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:24:06,811 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:24:09,667 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:24:11,271 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:24:12,513 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:24:15,316 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:24:16,509 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:24:16,517 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:24:16,567 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:24:16,568 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:24:18,198 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:24:21,071 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:24:22,078 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:24:24,110 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:24:26,865 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:24:26,865 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:24:27,133 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:24:29,699 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:24:30,508 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:24:31,528 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:24:31,571 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:24:31,573 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:24:32,448 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:24:32,448 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:24:32,987 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:24:35,167 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:24:35,167 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:24:35,458 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\output.log
2024-03-18 11:24:37,867 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:24:37,867 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:24:38,833 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:24:39,587 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\output.log
2024-03-18 11:24:40,699 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:24:43,644 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:24:43,906 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:24:46,484 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:24:46,509 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:24:46,544 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:24:46,584 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:24:46,586 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:24:49,162 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:24:49,350 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:24:52,125 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:24:52,125 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:24:54,181 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:24:54,950 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:24:57,699 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:24:57,699 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:24:59,258 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:25:00,525 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:25:00,653 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:25:01,538 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:25:01,614 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:25:01,615 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:25:03,509 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:25:05,044 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:25:06,515 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:25:09,454 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:25:10,205 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:25:12,429 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:25:15,269 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:25:15,291 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:25:16,616 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:25:16,616 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:25:16,623 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:25:18,153 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:25:21,144 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:25:21,150 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:25:24,021 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:25:24,021 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:25:26,346 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:25:26,846 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:25:29,602 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:25:29,604 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:25:30,567 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:25:31,557 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:25:31,558 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:25:31,629 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:25:31,629 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:25:32,405 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:25:32,405 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:25:35,218 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:25:36,993 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:25:38,107 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:25:40,231 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:25:42,086 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:25:43,045 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:25:45,880 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:25:46,582 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:25:46,631 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:25:46,635 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:25:48,026 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:25:48,807 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:25:50,282 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\output.log
2024-03-18 11:25:51,591 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:25:51,591 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:25:53,048 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:25:55,108 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:25:55,108 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:25:56,345 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\output.log
2024-03-18 11:25:57,858 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:25:57,858 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:25:58,968 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:26:00,579 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:26:00,612 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:26:00,614 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:26:01,584 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:26:01,616 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:26:01,627 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:26:03,554 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:04,420 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:26:06,405 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:09,228 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:09,525 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:26:12,074 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:14,591 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:26:14,899 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:16,619 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:26:16,667 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:26:16,667 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:26:17,725 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:20,270 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:26:20,581 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:23,410 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:25,344 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:26:26,221 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:28,956 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:26:28,960 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:26:30,379 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:26:30,602 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:26:31,616 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:26:31,648 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:26:31,648 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:26:31,893 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:34,629 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:26:34,633 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:26:36,067 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:26:37,427 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:26:37,427 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:26:40,321 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:41,150 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:26:43,172 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:46,012 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:46,490 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:26:46,637 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:26:46,676 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:26:46,676 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:26:48,862 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:51,687 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:52,106 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:26:54,575 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:26:57,169 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:26:57,341 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:26:57,341 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:27:00,137 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:27:00,139 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:27:00,609 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:27:01,639 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:27:01,674 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:27:01,676 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:27:02,884 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:27:02,884 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:27:03,102 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:27:05,729 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:27:08,224 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:27:08,655 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:27:11,540 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:27:13,328 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:27:14,403 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-18 11:27:16,172 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\output.log
2024-03-18 11:27:16,641 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:27:16,667 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 11:27:16,668 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: stop_status
2024-03-18 11:27:17,138 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:27:17,138 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:27:18,608 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:27:19,240 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\output.log
2024-03-18 11:27:19,539 DEBUG   SenderThread:26192 [sender.py:send():378] send: exit
2024-03-18 11:27:19,539 INFO    SenderThread:26192 [sender.py:send_exit():585] handling exit code: 0
2024-03-18 11:27:19,539 INFO    SenderThread:26192 [sender.py:send_exit():587] handling runtime: 500
2024-03-18 11:27:19,539 INFO    SenderThread:26192 [sender.py:_save_file():1365] saving file wandb-summary.json with policy end
2024-03-18 11:27:19,539 INFO    SenderThread:26192 [sender.py:send_exit():593] send defer
2024-03-18 11:27:19,539 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: defer
2024-03-18 11:27:19,539 INFO    HandlerThread:26192 [handler.py:handle_request_defer():172] handle defer: 0
2024-03-18 11:27:19,554 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: defer
2024-03-18 11:27:19,554 INFO    SenderThread:26192 [sender.py:send_request_defer():609] handle sender defer: 0
2024-03-18 11:27:19,555 INFO    SenderThread:26192 [sender.py:transition_state():613] send defer: 1
2024-03-18 11:27:19,555 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: defer
2024-03-18 11:27:19,555 INFO    HandlerThread:26192 [handler.py:handle_request_defer():172] handle defer: 1
2024-03-18 11:27:19,555 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: defer
2024-03-18 11:27:19,555 INFO    SenderThread:26192 [sender.py:send_request_defer():609] handle sender defer: 1
2024-03-18 11:27:19,555 INFO    SenderThread:26192 [sender.py:transition_state():613] send defer: 2
2024-03-18 11:27:19,555 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: defer
2024-03-18 11:27:19,555 INFO    HandlerThread:26192 [handler.py:handle_request_defer():172] handle defer: 2
2024-03-18 11:27:19,555 INFO    HandlerThread:26192 [system_monitor.py:finish():203] Stopping system monitor
2024-03-18 11:27:19,555 DEBUG   SystemMonitor:26192 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-18 11:27:19,555 DEBUG   SystemMonitor:26192 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-18 11:27:19,555 INFO    HandlerThread:26192 [interfaces.py:finish():202] Joined cpu monitor
2024-03-18 11:27:19,555 INFO    HandlerThread:26192 [interfaces.py:finish():202] Joined disk monitor
2024-03-18 11:27:19,808 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:27:19,808 ERROR   gpu       :26192 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-18 11:27:19,902 INFO    HandlerThread:26192 [interfaces.py:finish():202] Joined gpu monitor
2024-03-18 11:27:19,902 INFO    HandlerThread:26192 [interfaces.py:finish():202] Joined memory monitor
2024-03-18 11:27:19,902 INFO    HandlerThread:26192 [interfaces.py:finish():202] Joined network monitor
2024-03-18 11:27:19,902 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: defer
2024-03-18 11:27:19,902 INFO    SenderThread:26192 [sender.py:send_request_defer():609] handle sender defer: 2
2024-03-18 11:27:19,902 INFO    SenderThread:26192 [sender.py:transition_state():613] send defer: 3
2024-03-18 11:27:19,902 DEBUG   SenderThread:26192 [sender.py:send():378] send: stats
2024-03-18 11:27:19,902 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: defer
2024-03-18 11:27:19,902 INFO    HandlerThread:26192 [handler.py:handle_request_defer():172] handle defer: 3
2024-03-18 11:27:19,902 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: defer
2024-03-18 11:27:19,902 INFO    SenderThread:26192 [sender.py:send_request_defer():609] handle sender defer: 3
2024-03-18 11:27:19,902 INFO    SenderThread:26192 [sender.py:transition_state():613] send defer: 4
2024-03-18 11:27:19,902 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: defer
2024-03-18 11:27:19,902 INFO    HandlerThread:26192 [handler.py:handle_request_defer():172] handle defer: 4
2024-03-18 11:27:19,902 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: defer
2024-03-18 11:27:19,902 INFO    SenderThread:26192 [sender.py:send_request_defer():609] handle sender defer: 4
2024-03-18 11:27:19,902 INFO    SenderThread:26192 [sender.py:transition_state():613] send defer: 5
2024-03-18 11:27:19,902 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: defer
2024-03-18 11:27:19,902 INFO    HandlerThread:26192 [handler.py:handle_request_defer():172] handle defer: 5
2024-03-18 11:27:19,902 DEBUG   SenderThread:26192 [sender.py:send():378] send: summary
2024-03-18 11:27:19,902 INFO    SenderThread:26192 [sender.py:_save_file():1365] saving file wandb-summary.json with policy end
2024-03-18 11:27:19,902 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: defer
2024-03-18 11:27:19,902 INFO    SenderThread:26192 [sender.py:send_request_defer():609] handle sender defer: 5
2024-03-18 11:27:19,902 INFO    SenderThread:26192 [sender.py:transition_state():613] send defer: 6
2024-03-18 11:27:19,902 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: defer
2024-03-18 11:27:19,902 INFO    HandlerThread:26192 [handler.py:handle_request_defer():172] handle defer: 6
2024-03-18 11:27:19,902 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: defer
2024-03-18 11:27:19,902 INFO    SenderThread:26192 [sender.py:send_request_defer():609] handle sender defer: 6
2024-03-18 11:27:19,902 INFO    SenderThread:26192 [sender.py:transition_state():613] send defer: 7
2024-03-18 11:27:19,902 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 11:27:19,902 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: defer
2024-03-18 11:27:19,902 INFO    HandlerThread:26192 [handler.py:handle_request_defer():172] handle defer: 7
2024-03-18 11:27:19,902 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: defer
2024-03-18 11:27:19,902 INFO    SenderThread:26192 [sender.py:send_request_defer():609] handle sender defer: 7
2024-03-18 11:27:20,263 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\wandb-summary.json
2024-03-18 11:27:20,539 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-18 11:27:21,262 INFO    SenderThread:26192 [sender.py:transition_state():613] send defer: 8
2024-03-18 11:27:21,262 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: poll_exit
2024-03-18 11:27:21,262 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: defer
2024-03-18 11:27:21,271 INFO    HandlerThread:26192 [handler.py:handle_request_defer():172] handle defer: 8
2024-03-18 11:27:21,271 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: defer
2024-03-18 11:27:21,271 INFO    SenderThread:26192 [sender.py:send_request_defer():609] handle sender defer: 8
2024-03-18 11:27:21,271 INFO    SenderThread:26192 [job_builder.py:build():298] Attempting to build job artifact
2024-03-18 11:27:21,293 INFO    SenderThread:26192 [job_builder.py:_get_source_type():439] no source found
2024-03-18 11:27:21,293 INFO    SenderThread:26192 [sender.py:transition_state():613] send defer: 9
2024-03-18 11:27:21,293 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: defer
2024-03-18 11:27:21,293 INFO    HandlerThread:26192 [handler.py:handle_request_defer():172] handle defer: 9
2024-03-18 11:27:21,293 INFO    Thread-16 :26192 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\output.log
2024-03-18 11:27:21,293 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: defer
2024-03-18 11:27:21,303 INFO    SenderThread:26192 [sender.py:send_request_defer():609] handle sender defer: 9
2024-03-18 11:27:21,303 INFO    SenderThread:26192 [dir_watcher.py:finish():358] shutting down directory watcher
2024-03-18 11:27:21,556 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-18 11:27:22,306 INFO    SenderThread:26192 [dir_watcher.py:finish():388] scan: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files
2024-03-18 11:27:22,311 INFO    SenderThread:26192 [dir_watcher.py:finish():402] scan save: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\conda-environment.yaml conda-environment.yaml
2024-03-18 11:27:22,313 INFO    SenderThread:26192 [dir_watcher.py:finish():402] scan save: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\config.yaml config.yaml
2024-03-18 11:27:22,327 INFO    SenderThread:26192 [dir_watcher.py:finish():402] scan save: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\output.log output.log
2024-03-18 11:27:22,341 INFO    SenderThread:26192 [dir_watcher.py:finish():402] scan save: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\requirements.txt requirements.txt
2024-03-18 11:27:22,354 INFO    SenderThread:26192 [dir_watcher.py:finish():402] scan save: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\wandb-metadata.json wandb-metadata.json
2024-03-18 11:27:22,354 INFO    SenderThread:26192 [dir_watcher.py:finish():402] scan save: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\wandb-summary.json wandb-summary.json
2024-03-18 11:27:22,360 INFO    SenderThread:26192 [sender.py:transition_state():613] send defer: 10
2024-03-18 11:27:22,367 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: poll_exit
2024-03-18 11:27:22,369 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: defer
2024-03-18 11:27:22,369 INFO    HandlerThread:26192 [handler.py:handle_request_defer():172] handle defer: 10
2024-03-18 11:27:22,376 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: defer
2024-03-18 11:27:22,380 INFO    SenderThread:26192 [sender.py:send_request_defer():609] handle sender defer: 10
2024-03-18 11:27:22,383 INFO    SenderThread:26192 [file_pusher.py:finish():172] shutting down file pusher
2024-03-18 11:27:22,814 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-18 11:27:22,814 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: poll_exit
2024-03-18 11:27:23,549 INFO    wandb-upload_4:26192 [upload_job.py:push():131] Uploaded file C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\wandb-summary.json
2024-03-18 11:27:23,631 INFO    wandb-upload_1:26192 [upload_job.py:push():131] Uploaded file C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\config.yaml
2024-03-18 11:27:23,666 INFO    wandb-upload_2:26192 [upload_job.py:push():131] Uploaded file C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\output.log
2024-03-18 11:27:23,798 INFO    wandb-upload_3:26192 [upload_job.py:push():131] Uploaded file C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\requirements.txt
2024-03-18 11:27:23,823 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-18 11:27:23,826 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: poll_exit
2024-03-18 11:27:23,896 INFO    wandb-upload_0:26192 [upload_job.py:push():131] Uploaded file C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\files\conda-environment.yaml
2024-03-18 11:27:24,110 INFO    Thread-15 :26192 [sender.py:transition_state():613] send defer: 11
2024-03-18 11:27:24,112 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: defer
2024-03-18 11:27:24,112 INFO    HandlerThread:26192 [handler.py:handle_request_defer():172] handle defer: 11
2024-03-18 11:27:24,115 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: defer
2024-03-18 11:27:24,115 INFO    SenderThread:26192 [sender.py:send_request_defer():609] handle sender defer: 11
2024-03-18 11:27:24,115 INFO    SenderThread:26192 [file_pusher.py:join():178] waiting for file pusher
2024-03-18 11:27:24,142 INFO    SenderThread:26192 [sender.py:transition_state():613] send defer: 12
2024-03-18 11:27:24,143 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: defer
2024-03-18 11:27:24,144 INFO    HandlerThread:26192 [handler.py:handle_request_defer():172] handle defer: 12
2024-03-18 11:27:24,145 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: defer
2024-03-18 11:27:24,146 INFO    SenderThread:26192 [sender.py:send_request_defer():609] handle sender defer: 12
2024-03-18 11:27:24,146 INFO    SenderThread:26192 [file_stream.py:finish():595] file stream finish called
2024-03-18 11:27:24,829 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-18 11:27:25,130 INFO    SenderThread:26192 [file_stream.py:finish():599] file stream finish is done
2024-03-18 11:27:25,130 INFO    SenderThread:26192 [sender.py:transition_state():613] send defer: 13
2024-03-18 11:27:25,130 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: poll_exit
2024-03-18 11:27:25,130 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: defer
2024-03-18 11:27:25,130 INFO    HandlerThread:26192 [handler.py:handle_request_defer():172] handle defer: 13
2024-03-18 11:27:25,130 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: defer
2024-03-18 11:27:25,130 INFO    SenderThread:26192 [sender.py:send_request_defer():609] handle sender defer: 13
2024-03-18 11:27:25,130 INFO    SenderThread:26192 [sender.py:transition_state():613] send defer: 14
2024-03-18 11:27:25,130 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: defer
2024-03-18 11:27:25,146 INFO    HandlerThread:26192 [handler.py:handle_request_defer():172] handle defer: 14
2024-03-18 11:27:25,146 DEBUG   SenderThread:26192 [sender.py:send():378] send: final
2024-03-18 11:27:25,146 DEBUG   SenderThread:26192 [sender.py:send():378] send: footer
2024-03-18 11:27:25,146 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: defer
2024-03-18 11:27:25,146 INFO    SenderThread:26192 [sender.py:send_request_defer():609] handle sender defer: 14
2024-03-18 11:27:25,146 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-18 11:27:25,146 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: poll_exit
2024-03-18 11:27:25,146 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-18 11:27:25,146 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: server_info
2024-03-18 11:27:25,146 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: get_summary
2024-03-18 11:27:25,156 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: sampled_history
2024-03-18 11:27:25,156 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: poll_exit
2024-03-18 11:27:25,156 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 11:27:25,156 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: server_info
2024-03-18 11:27:25,156 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: job_info
2024-03-18 11:27:25,439 DEBUG   SenderThread:26192 [sender.py:send_request():405] send_request: job_info
2024-03-18 11:27:25,439 INFO    MainThread:26192 [wandb_run.py:_footer_history_summary_info():3851] rendering history
2024-03-18 11:27:25,439 INFO    MainThread:26192 [wandb_run.py:_footer_history_summary_info():3883] rendering summary
2024-03-18 11:27:25,439 INFO    MainThread:26192 [wandb_run.py:_footer_sync_info():3810] logging synced files
2024-03-18 11:27:25,455 DEBUG   HandlerThread:26192 [handler.py:handle_request():146] handle_request: shutdown
2024-03-18 11:27:25,455 INFO    HandlerThread:26192 [handler.py:finish():869] shutting down handler
2024-03-18 11:27:26,178 INFO    WriterThread:26192 [datastore.py:close():296] close: C:\Users\chinm\Desktop\FL-FINAL\MNIST\wandb\run-20240318_111854-9qdie3lg\run-9qdie3lg.wandb
2024-03-18 11:27:26,445 INFO    SenderThread:26192 [sender.py:finish():1521] shutting down sender
2024-03-18 11:27:26,445 INFO    SenderThread:26192 [file_pusher.py:finish():172] shutting down file pusher
2024-03-18 11:27:26,445 INFO    SenderThread:26192 [file_pusher.py:join():178] waiting for file pusher
