2024-03-28 00:14:45,226 INFO    StreamThr :21132 [internal.py:wandb_internal():86] W&B internal server running at pid: 21132, started at: 2024-03-28 00:14:45.222366
2024-03-28 00:14:45,235 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status
2024-03-28 00:14:45,254 INFO    WriterThread:21132 [datastore.py:open_for_write():87] open: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001445-ld6tbsp1\run-ld6tbsp1.wandb
2024-03-28 00:14:45,258 DEBUG   SenderThread:21132 [sender.py:send():378] send: header
2024-03-28 00:14:45,264 DEBUG   SenderThread:21132 [sender.py:send():378] send: run
2024-03-28 00:14:46,771 INFO    SenderThread:21132 [dir_watcher.py:__init__():211] watching files in: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001445-ld6tbsp1\files
2024-03-28 00:14:46,771 INFO    SenderThread:21132 [sender.py:_start_run_threads():1099] run started: ld6tbsp1 with start time 1711565085.232257
2024-03-28 00:14:46,822 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: check_version
2024-03-28 00:14:46,830 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: check_version
2024-03-28 00:14:47,460 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: run_start
2024-03-28 00:14:48,288 DEBUG   HandlerThread:21132 [system_info.py:__init__():26] System info init
2024-03-28 00:14:48,288 DEBUG   HandlerThread:21132 [system_info.py:__init__():41] System info init done
2024-03-28 00:14:48,288 INFO    HandlerThread:21132 [system_monitor.py:start():194] Starting system monitor
2024-03-28 00:14:48,288 INFO    SystemMonitor:21132 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-28 00:14:48,288 INFO    HandlerThread:21132 [system_monitor.py:probe():214] Collecting system info
2024-03-28 00:14:48,293 INFO    SystemMonitor:21132 [interfaces.py:start():190] Started cpu monitoring
2024-03-28 00:14:48,293 INFO    SystemMonitor:21132 [interfaces.py:start():190] Started disk monitoring
2024-03-28 00:14:48,293 INFO    SystemMonitor:21132 [interfaces.py:start():190] Started gpu monitoring
2024-03-28 00:14:48,293 INFO    SystemMonitor:21132 [interfaces.py:start():190] Started memory monitoring
2024-03-28 00:14:48,301 INFO    SystemMonitor:21132 [interfaces.py:start():190] Started network monitoring
2024-03-28 00:14:48,310 DEBUG   HandlerThread:21132 [system_info.py:probe():150] Probing system
2024-03-28 00:14:48,310 DEBUG   HandlerThread:21132 [gitlib.py:_init_repo():56] git repository is invalid
2024-03-28 00:14:48,310 DEBUG   HandlerThread:21132 [system_info.py:probe():198] Probing system done
2024-03-28 00:14:48,310 DEBUG   HandlerThread:21132 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.13', 'heartbeatAt': '2024-03-27T18:44:48.310744', 'startedAt': '2024-03-27T18:44:45.177027', 'docker': None, 'cuda': None, 'args': ('8000',), 'state': 'running', 'program': 'C:\\Users\\chinm\\Desktop\\FL-FINAL\\CIFAR\\server.py', 'codePathLocal': 'server.py', 'codePath': 'server.py', 'host': 'MSI', 'username': 'chinm', 'executable': 'C:\\Users\\chinm\\anaconda3\\New folder\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2496.0, 'min': 0.0, 'max': 2496.0}, 'cpu_freq_per_core': [{'current': 2496.0, 'min': 0.0, 'max': 2496.0}], 'disk': {'/': {'total': 458.81444931030273, 'used': 429.348331451416}}, 'gpu': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 7.8259735107421875}}
2024-03-28 00:14:48,310 INFO    HandlerThread:21132 [system_monitor.py:probe():224] Finished collecting system info
2024-03-28 00:14:48,310 INFO    HandlerThread:21132 [system_monitor.py:probe():227] Publishing system info
2024-03-28 00:14:48,310 DEBUG   HandlerThread:21132 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-03-28 00:14:48,319 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:14:48,790 INFO    Thread-16 :21132 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001445-ld6tbsp1\files\conda-environment.yaml
2024-03-28 00:14:50,950 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:14:50,950 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:14:53,589 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:14:53,589 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:14:56,215 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:14:56,215 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:14:58,851 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:14:58,851 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:01,482 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:01,482 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:04,110 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:04,110 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:05,693 DEBUG   HandlerThread:21132 [system_info.py:_save_conda():219] Saving conda packages done
2024-03-28 00:15:05,700 INFO    HandlerThread:21132 [system_monitor.py:probe():229] Finished publishing system info
2024-03-28 00:15:05,715 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:15:05,715 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:15:05,715 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:15:05,715 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:15:05,715 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:15:05,715 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:15:05,715 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:15:05,720 DEBUG   SenderThread:21132 [sender.py:send():378] send: files
2024-03-28 00:15:05,720 INFO    SenderThread:21132 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-03-28 00:15:05,900 INFO    Thread-16 :21132 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001445-ld6tbsp1\files\conda-environment.yaml
2024-03-28 00:15:05,900 INFO    Thread-16 :21132 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001445-ld6tbsp1\files\wandb-metadata.json
2024-03-28 00:15:06,748 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:06,750 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:06,779 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: python_packages
2024-03-28 00:15:06,779 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: python_packages
2024-03-28 00:15:06,779 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:15:06,788 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:15:06,788 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:15:06,918 INFO    Thread-16 :21132 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001445-ld6tbsp1\files\requirements.txt
2024-03-28 00:15:07,144 DEBUG   SenderThread:21132 [sender.py:send():378] send: telemetry
2024-03-28 00:15:07,193 INFO    wandb-upload_0:21132 [upload_job.py:push():131] Uploaded file C:\Users\chinm\AppData\Local\Temp\tmp4ekyffaewandb\v7y11mpi-wandb-metadata.json
2024-03-28 00:15:07,922 INFO    Thread-16 :21132 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001445-ld6tbsp1\files\output.log
2024-03-28 00:15:09,395 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:09,395 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:09,940 INFO    Thread-16 :21132 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001445-ld6tbsp1\files\output.log
2024-03-28 00:15:11,169 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:15:12,030 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:12,037 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:14,683 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:14,683 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:16,238 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:15:17,020 INFO    Thread-16 :21132 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001445-ld6tbsp1\files\config.yaml
2024-03-28 00:15:17,361 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:17,361 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:19,990 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:19,991 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:21,690 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:15:21,790 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:15:21,790 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:15:21,790 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:15:22,630 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:22,630 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:25,269 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:25,269 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:27,418 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:15:27,941 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:27,941 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:30,585 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:30,585 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:32,437 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:15:33,219 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:33,219 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:35,860 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:35,865 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:36,810 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:15:36,811 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:15:36,812 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:15:38,343 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:15:38,519 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:38,519 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:41,159 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:41,159 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:43,375 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:15:43,800 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:43,800 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:46,424 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:46,424 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:48,316 DEBUG   SystemMonitor:21132 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-28 00:15:48,316 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 00:15:49,047 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:49,047 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:49,323 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:15:51,663 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:51,663 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:51,803 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:15:51,803 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:15:51,835 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:15:54,311 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:54,311 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:54,715 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:15:56,964 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:56,964 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:15:58,967 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:15:59,745 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:01,248 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:01,248 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:03,861 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:03,861 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:04,793 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:06,514 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:06,514 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:06,821 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:16:06,821 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:16:06,836 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:16:09,086 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:09,086 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:10,351 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:11,760 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:11,760 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:14,416 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:14,416 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:15,387 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:17,039 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:17,039 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:17,620 INFO    Thread-16 :21132 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001445-ld6tbsp1\files\output.log
2024-03-28 00:16:18,320 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 00:16:19,694 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:19,694 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:21,336 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:21,841 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:16:21,842 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:16:21,842 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:16:22,335 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:22,335 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:24,996 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:24,996 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:27,342 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:27,640 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:27,640 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:30,262 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:30,262 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:32,397 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:32,892 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:32,892 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:35,511 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:35,511 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:36,847 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:16:36,847 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:16:36,847 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:16:38,150 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:38,150 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:38,347 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:40,796 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:40,796 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:43,031 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:43,031 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:43,384 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:45,683 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:16:45,689 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:45,689 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:48,266 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:48,266 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:48,328 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 00:16:49,335 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:50,879 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:50,894 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:51,847 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:16:51,847 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:16:51,862 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:16:53,513 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:53,513 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:55,230 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:16:56,126 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:56,126 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:58,768 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:16:58,768 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:00,273 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:01,387 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:01,387 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:04,007 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:04,007 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:05,407 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:06,167 INFO    Thread-16 :21132 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001445-ld6tbsp1\files\output.log
2024-03-28 00:17:06,683 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:06,683 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:06,857 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:17:06,857 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:17:06,872 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:17:09,348 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:09,348 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:10,464 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:12,009 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:12,009 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:14,647 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:14,647 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:15,495 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:17,296 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:17,305 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:18,339 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 00:17:19,920 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:19,920 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:21,382 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:21,885 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:17:21,885 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:17:21,885 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:17:22,586 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:22,586 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:25,247 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:17:25,263 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:25,263 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:27,385 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:27,883 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:27,883 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:30,565 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:30,565 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:32,415 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:32,884 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:32,885 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:35,574 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:35,574 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:36,898 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:17:36,898 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:17:36,900 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:17:37,442 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:38,252 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:38,252 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:40,945 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:40,945 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:42,492 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:43,601 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:43,603 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:46,273 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:46,273 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:47,515 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:48,362 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 00:17:48,955 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:48,955 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:51,655 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:51,656 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:51,899 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:17:51,903 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:17:51,906 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:17:52,726 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:54,327 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:54,328 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:56,992 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:56,997 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:57,791 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:17:59,717 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:17:59,717 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:02,403 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:02,403 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:02,846 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:05,295 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:18:05,314 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:18:06,915 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:18:06,915 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:18:06,915 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:18:07,801 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:07,807 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:08,328 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:10,513 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:10,513 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:13,231 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:13,232 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:13,388 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:15,969 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:18:18,370 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 00:18:18,610 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:18,610 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:19,385 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:21,270 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:21,275 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:21,942 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:18:21,945 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:18:21,945 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:18:23,958 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:23,963 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:25,345 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:26,645 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:26,650 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:29,339 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:29,339 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:30,418 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:32,135 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:18:34,748 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:34,748 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:35,507 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:36,925 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:18:36,927 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:18:36,954 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:18:37,477 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:37,477 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:40,101 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:40,101 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:41,435 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:42,804 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:42,804 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:45,626 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:18:46,505 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:48,173 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:48,174 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:48,389 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 00:18:50,875 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:50,875 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:51,925 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:18:51,927 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:18:51,958 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:18:52,516 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:53,536 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:53,544 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:56,257 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:56,257 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:57,557 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:18:58,918 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:18:58,918 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:01,621 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:01,621 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:02,606 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:04,290 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:04,290 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:06,933 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:19:06,933 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:19:06,974 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:19:06,988 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:06,988 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:08,385 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:09,631 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:09,631 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:12,326 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:12,326 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:13,422 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:15,003 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:15,003 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:17,702 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:17,702 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:18,418 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 00:19:19,445 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:20,392 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:20,392 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:21,954 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:19:21,954 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:19:21,986 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:19:23,096 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:23,096 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:24,469 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:26,028 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:19:28,467 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:28,467 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:29,544 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:31,086 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:31,086 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:33,779 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:33,779 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:34,610 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:36,436 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:36,450 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:36,953 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:19:36,956 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:19:36,995 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:19:39,102 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:39,102 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:40,138 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:41,800 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:41,800 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:44,482 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:44,498 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:45,177 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:47,239 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:19:48,789 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 00:19:49,880 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:49,880 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:50,896 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 00:19:51,592 WARNING FileStreamThread:21132 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000024FC3383DF0>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinnu1/flower_server/ld6tbsp1/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 8, 'content': ['{"system.proc.memory.availableMB": 1585.89, "system.memory": 80.22, "system.proc.memory.rssMB": 47.59, "system.proc.memory.percent": 0.59, "system.disk.\\\\.usagePercent": 94.4, "system.disk.\\\\.usageGB": 432.9, "system.disk.in": 3463.8, "system.disk.out": 1756.41, "system.cpu": 0.0, "system.cpu.0.cpu_percent": 20.51, "system.cpu.1.cpu_percent": 20.55, "system.cpu.2.cpu_percent": 30.11, "system.cpu.3.cpu_percent": 29.93, "system.cpu.4.cpu_percent": 17.39, "system.cpu.5.cpu_percent": 15.29, "system.cpu.6.cpu_percent": 18.29, "system.cpu.7.cpu_percent": 16.25, "system.cpu.8.cpu_percent": 19.61, "system.cpu.9.cpu_percent": 18.5, "system.cpu.10.cpu_percent": 89.97, "system.cpu.11.cpu_percent": 15.91, "system.proc.cpu.threads": 51, "system.network.sent": 731910.6, "system.network.recv": 5180431.13, "system.gpu.0.memoryAllocated": 2.56, "system.gpu.0.memoryAllocatedBytes": 110100480.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 60.0, "system.gpu.0.powerWatts": 16.27, "_wandb": true, "_timestamp": 1711565388.702591, "_runtime": 303.470334}']}}, 'dropped': 0}}
2024-03-28 00:19:51,998 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 00:19:52,003 DEBUG   SenderThread:21132 [sender.py:send_request():405] send_request: stop_status
2024-03-28 00:19:52,014 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:19:52,553 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:52,555 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:55,233 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:55,233 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:19:57,172 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:19:57,322 WARNING FileStreamThread:21132 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinnu1/flower_server/ld6tbsp1/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000024FC3383DF0>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinnu1/flower_server/ld6tbsp1/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 8, 'content': ['{"system.proc.memory.availableMB": 1585.89, "system.memory": 80.22, "system.proc.memory.rssMB": 47.59, "system.proc.memory.percent": 0.59, "system.disk.\\\\.usagePercent": 94.4, "system.disk.\\\\.usageGB": 432.9, "system.disk.in": 3463.8, "system.disk.out": 1756.41, "system.cpu": 0.0, "system.cpu.0.cpu_percent": 20.51, "system.cpu.1.cpu_percent": 20.55, "system.cpu.2.cpu_percent": 30.11, "system.cpu.3.cpu_percent": 29.93, "system.cpu.4.cpu_percent": 17.39, "system.cpu.5.cpu_percent": 15.29, "system.cpu.6.cpu_percent": 18.29, "system.cpu.7.cpu_percent": 16.25, "system.cpu.8.cpu_percent": 19.61, "system.cpu.9.cpu_percent": 18.5, "system.cpu.10.cpu_percent": 89.97, "system.cpu.11.cpu_percent": 15.91, "system.proc.cpu.threads": 51, "system.network.sent": 731910.6, "system.network.recv": 5180431.13, "system.gpu.0.memoryAllocated": 2.56, "system.gpu.0.memoryAllocatedBytes": 110100480.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 60.0, "system.gpu.0.powerWatts": 16.27, "_wandb": true, "_timestamp": 1711565388.702591, "_runtime": 303.470334}']}}, 'dropped': 0}}
2024-03-28 00:19:57,955 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:19:59,476 INFO    SenderThread:21132 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\connection.py", line 472, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\connection.py", line 545, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\util\ssl_match_hostname.py", line 155, in match_hostname
    raise CertificateError("hostname %r doesn't match %r" % (hostname, dnsnames[0]))
urllib3.util.ssl_match_hostname.CertificateError: hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\wandb\sdk\lib\gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\chinm\anaconda3\New folder\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'")))
2024-03-28 00:20:00,661 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:20:01,972 WARNING FileStreamThread:21132 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinnu1/flower_server/ld6tbsp1/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000024FC3383DF0>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinnu1/flower_server/ld6tbsp1/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 8, 'content': ['{"system.proc.memory.availableMB": 1585.89, "system.memory": 80.22, "system.proc.memory.rssMB": 47.59, "system.proc.memory.percent": 0.59, "system.disk.\\\\.usagePercent": 94.4, "system.disk.\\\\.usageGB": 432.9, "system.disk.in": 3463.8, "system.disk.out": 1756.41, "system.cpu": 0.0, "system.cpu.0.cpu_percent": 20.51, "system.cpu.1.cpu_percent": 20.55, "system.cpu.2.cpu_percent": 30.11, "system.cpu.3.cpu_percent": 29.93, "system.cpu.4.cpu_percent": 17.39, "system.cpu.5.cpu_percent": 15.29, "system.cpu.6.cpu_percent": 18.29, "system.cpu.7.cpu_percent": 16.25, "system.cpu.8.cpu_percent": 19.61, "system.cpu.9.cpu_percent": 18.5, "system.cpu.10.cpu_percent": 89.97, "system.cpu.11.cpu_percent": 15.91, "system.proc.cpu.threads": 51, "system.network.sent": 731910.6, "system.network.recv": 5180431.13, "system.gpu.0.memoryAllocated": 2.56, "system.gpu.0.memoryAllocatedBytes": 110100480.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 60.0, "system.gpu.0.powerWatts": 16.27, "_wandb": true, "_timestamp": 1711565388.702591, "_runtime": 303.470334}']}}, 'dropped': 0}}
2024-03-28 00:20:02,120 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:03,327 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:03,327 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:06,176 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:20:07,031 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:20:08,683 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:08,683 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:11,061 WARNING FileStreamThread:21132 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinnu1/flower_server/ld6tbsp1/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000024FC3383DF0>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinnu1/flower_server/ld6tbsp1/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 8, 'content': ['{"system.proc.memory.availableMB": 1585.89, "system.memory": 80.22, "system.proc.memory.rssMB": 47.59, "system.proc.memory.percent": 0.59, "system.disk.\\\\.usagePercent": 94.4, "system.disk.\\\\.usageGB": 432.9, "system.disk.in": 3463.8, "system.disk.out": 1756.41, "system.cpu": 0.0, "system.cpu.0.cpu_percent": 20.51, "system.cpu.1.cpu_percent": 20.55, "system.cpu.2.cpu_percent": 30.11, "system.cpu.3.cpu_percent": 29.93, "system.cpu.4.cpu_percent": 17.39, "system.cpu.5.cpu_percent": 15.29, "system.cpu.6.cpu_percent": 18.29, "system.cpu.7.cpu_percent": 16.25, "system.cpu.8.cpu_percent": 19.61, "system.cpu.9.cpu_percent": 18.5, "system.cpu.10.cpu_percent": 89.97, "system.cpu.11.cpu_percent": 15.91, "system.proc.cpu.threads": 51, "system.network.sent": 731910.6, "system.network.recv": 5180431.13, "system.gpu.0.memoryAllocated": 2.56, "system.gpu.0.memoryAllocatedBytes": 110100480.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 60.0, "system.gpu.0.powerWatts": 16.27, "_wandb": true, "_timestamp": 1711565388.702591, "_runtime": 303.470334}']}}, 'dropped': 0}}
2024-03-28 00:20:11,390 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:11,390 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:12,221 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:14,044 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:14,044 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:16,694 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:16,694 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:17,291 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:19,388 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:19,394 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:22,045 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:20:22,060 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:22,063 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:24,758 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:24,758 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:27,363 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:27,379 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:27,409 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:29,878 WARNING FileStreamThread:21132 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinnu1/flower_server/ld6tbsp1/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000024FC3383DF0>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinnu1/flower_server/ld6tbsp1/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 8, 'content': ['{"system.proc.memory.availableMB": 1585.89, "system.memory": 80.22, "system.proc.memory.rssMB": 47.59, "system.proc.memory.percent": 0.59, "system.disk.\\\\.usagePercent": 94.4, "system.disk.\\\\.usageGB": 432.9, "system.disk.in": 3463.8, "system.disk.out": 1756.41, "system.cpu": 0.0, "system.cpu.0.cpu_percent": 20.51, "system.cpu.1.cpu_percent": 20.55, "system.cpu.2.cpu_percent": 30.11, "system.cpu.3.cpu_percent": 29.93, "system.cpu.4.cpu_percent": 17.39, "system.cpu.5.cpu_percent": 15.29, "system.cpu.6.cpu_percent": 18.29, "system.cpu.7.cpu_percent": 16.25, "system.cpu.8.cpu_percent": 19.61, "system.cpu.9.cpu_percent": 18.5, "system.cpu.10.cpu_percent": 89.97, "system.cpu.11.cpu_percent": 15.91, "system.proc.cpu.threads": 51, "system.network.sent": 731910.6, "system.network.recv": 5180431.13, "system.gpu.0.memoryAllocated": 2.56, "system.gpu.0.memoryAllocatedBytes": 110100480.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 60.0, "system.gpu.0.powerWatts": 16.27, "_wandb": true, "_timestamp": 1711565388.702591, "_runtime": 303.470334}']}}, 'dropped': 0}}
2024-03-28 00:20:30,056 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:30,056 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:32,442 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:32,730 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:32,730 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:35,403 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:35,403 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:37,038 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:20:38,114 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:38,114 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:40,797 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:40,797 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:42,571 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:43,475 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:43,475 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:46,211 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:20:47,633 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:48,746 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:48,746 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:51,361 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:51,361 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:52,052 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:20:53,999 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:53,999 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:56,625 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:56,641 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:57,726 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:20:59,301 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:20:59,301 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:01,940 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:01,940 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:02,758 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:04,582 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:04,582 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:04,770 WARNING FileStreamThread:21132 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinnu1/flower_server/ld6tbsp1/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000024FC3383DF0>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinnu1/flower_server/ld6tbsp1/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 8, 'content': ['{"system.proc.memory.availableMB": 1585.89, "system.memory": 80.22, "system.proc.memory.rssMB": 47.59, "system.proc.memory.percent": 0.59, "system.disk.\\\\.usagePercent": 94.4, "system.disk.\\\\.usageGB": 432.9, "system.disk.in": 3463.8, "system.disk.out": 1756.41, "system.cpu": 0.0, "system.cpu.0.cpu_percent": 20.51, "system.cpu.1.cpu_percent": 20.55, "system.cpu.2.cpu_percent": 30.11, "system.cpu.3.cpu_percent": 29.93, "system.cpu.4.cpu_percent": 17.39, "system.cpu.5.cpu_percent": 15.29, "system.cpu.6.cpu_percent": 18.29, "system.cpu.7.cpu_percent": 16.25, "system.cpu.8.cpu_percent": 19.61, "system.cpu.9.cpu_percent": 18.5, "system.cpu.10.cpu_percent": 89.97, "system.cpu.11.cpu_percent": 15.91, "system.proc.cpu.threads": 51, "system.network.sent": 731910.6, "system.network.recv": 5180431.13, "system.gpu.0.memoryAllocated": 2.56, "system.gpu.0.memoryAllocatedBytes": 110100480.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 60.0, "system.gpu.0.powerWatts": 16.27, "_wandb": true, "_timestamp": 1711565388.702591, "_runtime": 303.470334}']}}, 'dropped': 0}}
2024-03-28 00:21:07,069 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:21:07,210 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:07,210 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:09,865 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:09,865 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:12,490 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:12,490 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:12,820 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:15,131 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:15,131 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:17,785 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:17,785 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:17,848 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:20,420 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:20,420 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:22,073 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:21:23,064 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:23,064 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:25,725 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:25,725 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:27,910 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:28,332 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:28,332 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:30,972 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:30,972 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:32,938 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:33,612 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:33,612 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:36,252 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:36,252 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:37,087 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:21:38,892 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:38,892 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:41,533 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:41,533 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:42,997 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:44,172 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:44,172 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:46,813 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:46,813 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:48,024 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:49,438 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:49,438 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:51,466 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 00:21:52,095 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:21:54,110 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:54,110 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:56,729 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:56,729 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:58,082 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:21:59,370 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:21:59,370 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:02,010 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:02,010 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:03,110 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:04,701 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:04,701 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:07,104 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:22:07,293 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:07,293 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:09,929 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:09,929 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:12,163 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:12,570 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:12,570 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:15,211 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:15,211 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:15,985 WARNING FileStreamThread:21132 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinnu1/flower_server/ld6tbsp1/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000024FC3383DF0>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinnu1/flower_server/ld6tbsp1/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 8, 'content': ['{"system.proc.memory.availableMB": 1585.89, "system.memory": 80.22, "system.proc.memory.rssMB": 47.59, "system.proc.memory.percent": 0.59, "system.disk.\\\\.usagePercent": 94.4, "system.disk.\\\\.usageGB": 432.9, "system.disk.in": 3463.8, "system.disk.out": 1756.41, "system.cpu": 0.0, "system.cpu.0.cpu_percent": 20.51, "system.cpu.1.cpu_percent": 20.55, "system.cpu.2.cpu_percent": 30.11, "system.cpu.3.cpu_percent": 29.93, "system.cpu.4.cpu_percent": 17.39, "system.cpu.5.cpu_percent": 15.29, "system.cpu.6.cpu_percent": 18.29, "system.cpu.7.cpu_percent": 16.25, "system.cpu.8.cpu_percent": 19.61, "system.cpu.9.cpu_percent": 18.5, "system.cpu.10.cpu_percent": 89.97, "system.cpu.11.cpu_percent": 15.91, "system.proc.cpu.threads": 51, "system.network.sent": 731910.6, "system.network.recv": 5180431.13, "system.gpu.0.memoryAllocated": 2.56, "system.gpu.0.memoryAllocatedBytes": 110100480.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 60.0, "system.gpu.0.powerWatts": 16.27, "_wandb": true, "_timestamp": 1711565388.702591, "_runtime": 303.470334}']}}, 'dropped': 0}}
2024-03-28 00:22:17,195 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:17,851 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:17,851 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:20,510 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:20,510 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:22,114 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:22:23,134 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:23,134 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:25,770 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:25,770 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:27,249 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:28,409 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:28,409 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:31,051 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:31,051 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:32,276 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:33,690 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:33,690 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:36,328 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:36,328 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:37,129 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:22:38,950 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:38,950 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:41,600 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:41,600 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:42,340 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:44,260 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:22:44,275 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:44,275 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:46,884 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:46,884 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:47,371 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:49,523 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:49,523 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:52,147 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:22:52,163 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:52,163 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:54,818 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:54,818 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:57,423 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:22:57,460 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:22:57,460 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:00,093 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:00,093 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:02,448 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:02,731 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:02,731 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:05,368 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:05,377 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:07,159 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:23:08,008 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:08,008 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:10,651 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:10,651 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:12,504 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:13,306 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:13,306 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:15,963 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:15,963 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:17,536 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:18,589 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:18,589 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:21,234 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:21,234 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:22,162 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:23:23,907 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:23:23,923 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:23,923 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:26,512 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:26,512 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:27,597 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:29,154 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:29,154 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:31,804 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:31,804 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:32,631 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:34,444 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:34,449 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:37,087 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:37,087 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:37,165 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:23:39,743 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:39,759 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:42,386 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:42,386 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:42,700 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:45,024 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:45,024 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:47,668 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:47,668 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:47,728 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:50,306 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:50,306 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:52,176 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:23:52,945 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:52,945 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:55,570 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:55,570 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:57,784 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:23:58,224 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:23:58,224 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:00,913 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:00,913 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:02,810 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:03,580 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:24:03,596 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:03,596 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:06,234 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:06,234 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:07,192 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:24:08,874 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:08,889 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:11,545 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:11,545 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:12,863 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:14,213 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:14,213 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:16,900 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:16,900 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:17,891 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:19,573 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:19,573 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:22,194 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:24:22,241 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:22,241 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:24,894 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:24,894 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:27,251 WARNING FileStreamThread:21132 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinnu1/flower_server/ld6tbsp1/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000024FC3383DF0>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinnu1/flower_server/ld6tbsp1/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 8, 'content': ['{"system.proc.memory.availableMB": 1585.89, "system.memory": 80.22, "system.proc.memory.rssMB": 47.59, "system.proc.memory.percent": 0.59, "system.disk.\\\\.usagePercent": 94.4, "system.disk.\\\\.usageGB": 432.9, "system.disk.in": 3463.8, "system.disk.out": 1756.41, "system.cpu": 0.0, "system.cpu.0.cpu_percent": 20.51, "system.cpu.1.cpu_percent": 20.55, "system.cpu.2.cpu_percent": 30.11, "system.cpu.3.cpu_percent": 29.93, "system.cpu.4.cpu_percent": 17.39, "system.cpu.5.cpu_percent": 15.29, "system.cpu.6.cpu_percent": 18.29, "system.cpu.7.cpu_percent": 16.25, "system.cpu.8.cpu_percent": 19.61, "system.cpu.9.cpu_percent": 18.5, "system.cpu.10.cpu_percent": 89.97, "system.cpu.11.cpu_percent": 15.91, "system.proc.cpu.threads": 51, "system.network.sent": 731910.6, "system.network.recv": 5180431.13, "system.gpu.0.memoryAllocated": 2.56, "system.gpu.0.memoryAllocatedBytes": 110100480.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 60.0, "system.gpu.0.powerWatts": 16.27, "_wandb": true, "_timestamp": 1711565388.702591, "_runtime": 303.470334}']}}, 'dropped': 0}}
2024-03-28 00:24:27,549 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:27,565 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:27,942 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:30,234 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:30,234 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:32,886 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:32,886 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:32,964 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:35,568 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:35,568 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:37,203 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:24:38,222 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:38,222 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:40,877 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:40,877 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:43,012 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:43,577 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:24:43,577 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:43,577 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:46,205 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:46,205 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:48,039 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:48,872 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:48,872 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:51,544 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:51,544 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:52,219 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:24:54,196 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:54,196 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:56,867 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:56,867 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:58,089 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:24:59,534 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:24:59,534 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:02,196 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:02,196 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:03,122 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:04,881 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:04,882 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:07,234 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:25:07,532 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:07,532 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:10,202 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:10,202 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:12,863 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:12,863 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:13,169 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:15,511 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:15,511 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:18,173 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:18,173 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:18,195 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:20,845 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:20,845 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:22,244 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:25:23,516 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:25:23,531 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:23,531 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:26,167 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:26,167 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:27,236 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:28,822 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:28,822 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:31,503 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:31,503 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:32,255 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:34,154 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:34,154 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:36,835 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:36,835 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:37,259 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:25:39,487 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:39,487 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:42,172 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:42,172 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:42,297 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:44,833 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:44,833 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:47,320 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:47,493 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:47,493 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:50,177 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:50,177 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:52,268 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:25:52,833 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:52,833 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:55,487 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:55,503 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:57,372 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:25:58,172 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:25:58,172 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:00,823 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:00,823 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:02,394 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:03,534 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:26:03,547 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:03,547 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:06,159 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:06,159 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:07,274 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:26:08,811 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:08,811 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:11,462 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:11,462 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:12,436 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:14,130 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:14,130 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:16,801 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:16,801 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:17,458 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:19,465 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:19,481 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:22,134 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:22,134 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:22,276 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:26:24,792 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:24,792 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:27,444 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:27,444 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:27,506 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:30,097 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:30,097 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:32,527 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:32,783 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:32,783 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:35,435 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:35,435 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:37,284 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:26:38,087 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:38,087 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:40,757 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:40,757 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:42,577 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:43,457 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:26:43,457 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:43,457 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:46,094 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:46,094 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:47,599 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:48,776 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:48,776 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:51,429 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:51,429 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:52,292 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:26:54,082 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:54,082 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:56,751 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:56,766 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:57,649 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:26:59,421 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:26:59,421 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:02,112 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:02,113 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:02,669 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:04,772 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:04,772 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:07,300 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:27:07,442 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:07,442 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:10,094 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:10,094 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:12,717 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:12,748 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:12,748 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:15,415 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:15,415 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:17,741 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:18,083 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:18,085 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:20,725 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:20,725 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:22,310 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:27:23,411 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:27:23,430 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:23,430 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:26,063 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:26,063 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:27,789 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:28,716 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:28,716 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:31,385 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:31,385 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:32,812 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:34,067 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:34,067 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:36,718 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:36,718 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:37,315 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:27:39,387 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:39,387 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:42,065 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:42,072 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:42,857 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:44,743 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:44,743 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:47,398 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:47,398 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:47,885 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:50,063 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:50,078 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:52,324 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:27:52,733 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:52,733 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:55,389 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:55,404 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:57,931 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:27:58,072 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:27:58,072 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:00,725 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:00,725 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:02,955 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:03,410 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:28:03,424 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:03,426 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:06,046 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:06,046 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:07,333 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:28:08,717 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:08,717 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:11,380 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:11,380 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:12,997 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:14,034 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:14,034 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:16,701 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:16,701 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:18,016 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:19,382 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:19,382 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:22,034 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:22,034 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:22,349 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:28:24,704 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:24,704 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:27,386 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:27,386 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:28,062 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:30,056 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:30,056 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:32,718 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:32,718 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:33,080 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:35,372 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:35,372 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:37,365 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:28:38,025 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:38,025 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:40,694 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:40,694 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:43,128 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:43,395 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 00:28:43,395 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:43,395 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:46,036 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:46,036 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:48,151 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:48,703 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:48,703 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:51,353 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:51,353 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:52,373 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:28:54,022 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:54,022 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:55,403 WARNING FileStreamThread:21132 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/chinnu1/flower_server/ld6tbsp1/file_stream (Caused by SSLError(CertificateError("hostname 'api.wandb.ai' doesn't match 'fnac.nitk.ac.in'"))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000024FC3383DF0>>, timeout=180.0), args: ('https://api.wandb.ai/files/chinnu1/flower_server/ld6tbsp1/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 8, 'content': ['{"system.proc.memory.availableMB": 1585.89, "system.memory": 80.22, "system.proc.memory.rssMB": 47.59, "system.proc.memory.percent": 0.59, "system.disk.\\\\.usagePercent": 94.4, "system.disk.\\\\.usageGB": 432.9, "system.disk.in": 3463.8, "system.disk.out": 1756.41, "system.cpu": 0.0, "system.cpu.0.cpu_percent": 20.51, "system.cpu.1.cpu_percent": 20.55, "system.cpu.2.cpu_percent": 30.11, "system.cpu.3.cpu_percent": 29.93, "system.cpu.4.cpu_percent": 17.39, "system.cpu.5.cpu_percent": 15.29, "system.cpu.6.cpu_percent": 18.29, "system.cpu.7.cpu_percent": 16.25, "system.cpu.8.cpu_percent": 19.61, "system.cpu.9.cpu_percent": 18.5, "system.cpu.10.cpu_percent": 89.97, "system.cpu.11.cpu_percent": 15.91, "system.proc.cpu.threads": 51, "system.network.sent": 731910.6, "system.network.recv": 5180431.13, "system.gpu.0.memoryAllocated": 2.56, "system.gpu.0.memoryAllocatedBytes": 110100480.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 60.0, "system.gpu.0.powerWatts": 16.27, "_wandb": true, "_timestamp": 1711565388.702591, "_runtime": 303.470334}']}}, 'dropped': 0}}
2024-03-28 00:28:56,692 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:56,692 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:58,198 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:28:59,381 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:28:59,381 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:29:02,043 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:29:02,044 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:29:03,223 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:29:04,479 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:29:04,479 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:44:05,748 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 00:44:06,658 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:44:06,658 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 00:44:06,878 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 00:44:08,701 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:29:56,183 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:29:57,113 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-28 09:29:59,484 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:29:59,484 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:01,307 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:01,543 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:01,543 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:04,183 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:04,183 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:06,346 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:06,880 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:06,880 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:08,263 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:30:09,469 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:09,469 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:12,078 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:12,078 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:13,383 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:14,719 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:14,719 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:17,345 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:17,345 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:18,416 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:19,969 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:19,979 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:22,608 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:22,608 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:23,265 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:30:25,249 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:25,249 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:27,871 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:27,871 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:28,264 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:30,503 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:30,503 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:33,125 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:33,125 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:33,502 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:35,751 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:35,751 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:38,280 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:30:38,374 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:38,374 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:41,023 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:41,023 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:43,555 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:43,634 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:43,634 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:46,307 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 09:30:46,322 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:46,322 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:48,583 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:48,897 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:48,897 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:51,523 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:51,523 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:53,283 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:30:54,151 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:54,151 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:56,771 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:56,771 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:58,296 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:30:59,406 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:30:59,406 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:02,062 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:02,062 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:03,663 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:04,717 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:04,717 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:07,387 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:07,387 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:08,298 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:31:10,041 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:10,041 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:12,696 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:12,696 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:13,309 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:15,335 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:15,351 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:18,007 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:18,007 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:18,743 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:20,657 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:20,657 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:23,310 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:31:23,310 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:23,310 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:25,995 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 09:31:26,010 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:26,010 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:28,317 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:28,632 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:28,632 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:31,304 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:31,305 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:33,817 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:33,975 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:33,975 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:36,633 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:36,633 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:38,317 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:31:39,290 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:39,290 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:41,960 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:41,960 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:43,340 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:44,626 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:44,626 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:47,317 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:47,317 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:48,903 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:31:49,939 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:49,939 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:52,596 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:52,596 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:53,319 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:31:55,220 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:55,220 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:57,844 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:57,844 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:31:58,363 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:00,486 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:00,486 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:03,130 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:03,131 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:03,993 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:05,787 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 09:32:05,803 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:05,803 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:08,327 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:32:08,405 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:08,405 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:11,061 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:11,061 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:13,373 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:13,687 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:13,687 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:16,328 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:16,328 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:18,967 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:18,967 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:19,077 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:21,607 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:21,607 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:23,336 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:32:24,247 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:24,247 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:26,871 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:26,871 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:28,381 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:29,510 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:29,510 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:32,150 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:32,150 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:34,161 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:34,790 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:34,790 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:37,429 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:37,429 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:38,340 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:32:40,068 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:40,068 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:42,709 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:42,709 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:43,384 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:45,362 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 09:32:45,377 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:45,377 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:47,987 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:47,987 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:49,244 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:50,625 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:50,625 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:53,264 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:53,264 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:53,343 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:32:55,900 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:55,900 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:58,396 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:32:58,537 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:32:58,537 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:01,207 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:01,209 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:03,846 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:03,846 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:04,319 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:06,533 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:06,533 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:08,357 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:33:09,172 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:09,172 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:11,797 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:11,797 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:13,387 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:14,445 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:14,445 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:17,083 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:17,090 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:18,437 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:19,740 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:19,740 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:22,394 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:22,394 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:23,368 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:33:25,079 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 09:33:25,095 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:25,095 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:27,686 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:27,686 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:28,425 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:30,338 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:30,338 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:32,982 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:32,982 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:33,549 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:35,630 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:35,630 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:38,269 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:38,269 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:38,379 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:33:40,928 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:40,928 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:43,428 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:43,569 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:43,569 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:46,216 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:46,216 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:48,654 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:48,859 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:48,859 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:51,497 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:51,497 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:53,383 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:33:54,135 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:54,135 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:56,764 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:56,764 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:58,427 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:33:59,399 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:33:59,399 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:02,038 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:02,038 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:03,737 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:04,696 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 09:34:04,712 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:04,712 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:07,308 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:07,308 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:08,387 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:34:09,954 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:09,954 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:12,596 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:12,596 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:13,429 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:15,221 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:15,221 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:17,861 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:17,861 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:18,820 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:20,502 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:20,502 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:23,131 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:23,131 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:23,393 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:34:25,764 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:25,764 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:28,405 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:28,405 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:28,436 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:31,051 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:31,051 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:33,688 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:33,688 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:33,908 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:36,327 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:36,327 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:38,403 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:34:38,480 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,482 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:34:38,482 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,482 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,482 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,482 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,482 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,482 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,491 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,491 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,491 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,491 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,491 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,491 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,491 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,498 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,498 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,502 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,502 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,502 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,502 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,502 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,507 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,508 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,509 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,510 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,511 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,512 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,513 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:34:38,973 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:38,973 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:40,338 INFO    Thread-16 :21132 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\chinm\Desktop\FL-FINAL\CIFAR\wandb\run-20240328_001445-ld6tbsp1\files\output.log
2024-03-28 09:34:41,624 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:41,624 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:43,451 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:43,544 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:34:44,299 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 09:34:44,299 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:44,299 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:46,932 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:46,932 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:48,571 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:34:49,003 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:49,571 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:49,571 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:52,217 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:52,217 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:53,417 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 09:34:53,622 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:34:54,848 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:54,848 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:57,521 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:57,521 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:34:58,490 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:34:58,680 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:35:00,174 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:00,174 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:02,828 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:02,828 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:03,722 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 09:35:04,119 DEBUG   HandlerThread:21132 [handler.py:handle_request():146] handle_request: keepalive
2024-03-28 09:35:04,843 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:35:05,471 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:05,471 ERROR   gpu       :21132 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-03-28 09:35:05,775 INFO    cpu       :21132 [interfaces.py:monitor():140] Process cpu has exited.
2024-03-28 09:35:05,775 DEBUG   SystemMonitor:21132 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-28 09:35:05,775 DEBUG   SystemMonitor:21132 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-28 09:35:05,775 ERROR   gpu       :21132 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-28 09:35:05,775 DEBUG   SenderThread:21132 [sender.py:send():378] send: stats
2024-03-28 09:35:07,624 INFO    MainThread:21132 [internal.py:handle_exit():76] Internal process exited
